/* Umrah Strivers smoke tests — run: npm test  (needs Chromium; set CHROME=/path/to/chromium if not auto-detected) */
const path = require('path');
const { chromium } = require('playwright-core');
const URL = 'file://' + path.resolve(__dirname, '../index.html');
const exe = process.env.CHROME || process.env.PLAYWRIGHT_CHROMIUM || (process.env.PLAYWRIGHT_BROWSERS_PATH ? process.env.PLAYWRIGHT_BROWSERS_PATH + '/chromium' : undefined);
const PT = { data: { timings: { Fajr: '05:12', Dhuhr: '12:21', Asr: '15:42', Maghrib: '18:33', Isha: '20:03' }, date: { hijri: { day: '24', month: { en: 'Rabi al-Awwal' }, year: '1448' } } } };
let failed = 0;
function check(name, cond, extra) { console.log((cond ? '  ✓ ' : '  ✗ ') + name + (cond ? '' : '  ' + JSON.stringify(extra || ''))); if (!cond) failed++; }

(async () => {
  const browser = await chromium.launch({ executablePath: exe });
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, geolocation: { latitude: 21.42, longitude: 39.83 }, permissions: ['geolocation'] });
  const page = await ctx.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', d => d.accept());
  await page.route('**/api.aladhan.com/**', r => r.fulfill({ contentType: 'application/json', headers: { 'access-control-allow-origin': '*' }, body: JSON.stringify(PT) }));
  await page.goto(URL);
  await page.evaluate(() => localStorage.setItem('us-settings', JSON.stringify({ onboarded: true, name: 'Test', dep: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10), tripLen: 10, day: 1 })));
  await page.reload(); await page.waitForTimeout(900);

  console.log('Home');
  check('opens on Home', (await page.getAttribute('.view.on', 'id')) === 'view-home');
  check('journey chip counts down + no update chip', (await page.textContent('#jChip')).includes('day') && (await page.locator('#updChip').isHidden()));
  check('explains the app + greets by name', (await page.textContent('.hhero h2')).includes('Umrah companion') && (await page.textContent('.hs-t')).includes('Test') && (await page.locator('.stage').count()) === 5);
  check('next prayer loaded', (await page.textContent('#hNext')).includes('in '));
  check('9 quick actions + the wide Hotel / SOS row', (await page.locator('.qa').count()) === 10 && (await page.locator('.qa.wide').count()) === 1);

  console.log('Plan');
  await page.evaluate(() => { goTab('plan'); goSub('plan', 'prep', true); });
  await page.click('#pw-passport');
  check('checklist ticks', (await page.locator('#pw-passport.done').count()) === 1);
  check('itinerary renders 10 days', (await page.locator('.it').count()) === 10);
  check('timeline: blocking items first, capped groups, neutral late pills', (await page.textContent('#tlArea')).includes('Should already be done') && (await page.locator('.tli-more').count()) >= 1 && (await page.locator('.tli-when.over').count()) <= 5 && (await page.locator('#prepJumps button').count()) === 7);
  await page.click('.tli >> nth=0'); await page.waitForTimeout(600);
  const tickedBefore = await page.evaluate(() => Object.keys(planChk).filter(k => planChk[k]).length);
  await page.click('.toast.act button:has-text("Undo")'); await page.waitForTimeout(200);
  check('timeline tick offers Undo', tickedBefore === 2 && (await page.evaluate(() => Object.keys(planChk).filter(k => planChk[k]).length)) === 1);
  await page.evaluate(() => setProfile('w'));
  check('sister profile hides men-only rows and adds sisters\u2019 items', (await page.locator('#pw-ihram').count()) === 0 && (await page.locator('#pw-scissors').count()) === 1 && (await page.locator('#rw-cut').count()) === 0 && (await page.locator('#rw-cutw').count()) === 1);
  await page.evaluate(() => { setProfile(''); togKids(); });
  check('children toggle adds a 5th checklist + tile', (await page.locator('#sec-kids .row').count()) === 8 && (await page.locator('#catTiles .st').count()) === 5);
  await page.evaluate(() => togKids());
  await page.fill('#hName', 'Swiss\u00f4tel Makkah'); await page.fill('#hLead', 'Ahmed \u00b7 +966 55 123 4567'); await page.dispatchEvent('#hLead', 'change');
  await page.evaluate(() => showLost()); await page.waitForTimeout(200);
  check('I\u2019m lost overlay: leader tel link + 911/1966', (await page.locator('#lost.on .lost-tel[href="tel:+966551234567"]').count()) === 1 && (await page.locator('#lost a[href="tel:911"]').count()) === 1 && (await page.locator('#lost a[href="tel:1966"]').count()) === 1);
  await page.evaluate(() => { closeLost(); showDriver(); });
  check('driver card has Call + Maps actions', (await page.locator('#driver.on #drvActs a[href^="https://www.google.com/maps/dir/"]').count()) === 1);
  await page.evaluate(() => closeDriver());
  await page.evaluate(() => goSub('plan', 'learn', true));
  check('knowledge accordions', (await page.locator('#histCard .acc').count()) >= 9 && (await page.locator('#qaContainer .acc').count()) === 10 && (await page.locator('#scamContainer .acc').count()) === 10);
  check('flashcards due', (await page.textContent('#fcArea')).includes('Review'));
  await page.evaluate(() => goSub('plan', 'quiz', true));
  check('7 quiz levels, 6 locked', (await page.locator('.lvl').count()) === 7 && (await page.locator('.lvl.locked').count()) === 6);
  await page.click('.lvl >> nth=0');
  const n1 = await page.evaluate(() => QUIZ_LEVELS[0].qs.length);
  for (let k = 0; k < n1; k++) { const c = await page.evaluate(kk => { const q = QUIZ_LEVELS[0].qs[kk]; return q.o ? q.a : (q.a === 0 ? 0 : 1); }, k); await page.click('#qzo-' + c); await page.click('#qzFb .btn'); }
  check('level 1 passed at 100%', (await page.textContent('.qz-final .big')) === '100%');
  await page.click('text=← All levels');
  check('level 2 unlocked', (await page.locator('.lvl.locked').count()) === 5);

  console.log('Umrah');
  await page.evaluate(() => { goTab('umrah'); goSub('umrah', 'count', true); });
  for (let i = 0; i < 7; i++) await page.click('.tapring >> nth=0');
  check('tawaf counter reaches 7', (await page.textContent('#tawafN')) === '7' && await page.isVisible('#tawafDone'));
  await page.evaluate(() => { togRite('niyyah'); for (let i = 0; i < 7; i++) cntr('sai', 1); togRite('cut'); });
  check('timeline stamped', (await page.locator('#logArea .lg.on').count()) === 6);
  await page.click('text=⛶ Focus >> nth=0');
  check('focus mode opens', (await page.locator('#focus.on').count()) === 1);
  await page.click('text=✕ Exit');
  await page.evaluate(() => goSub('umrah', 'steps', true));
  await page.click('#rw-ghusl .why');
  check('why explainer toggles', (await page.locator('#rw-ghusl .whyb.on').count()) === 1);
  await page.click('button.btn.gold:has-text("Record completed Umrah")'); await page.waitForTimeout(300);
  await page.evaluate(() => goSub('umrah', 'steps', true)); await page.click('#umrahsArea .chip-btn'); await page.waitForTimeout(300);
  check('keepsake opens the export sheet with preview', (await page.locator('#gSheet.on img').count()) === 1);
  const dl1 = page.waitForEvent('download', { timeout: 6000 }).catch(() => null);
  await page.click('#gSheet button:has-text("Download")');
  check('umrah recorded + keepsake downloads', (await page.evaluate(() => ST.umrahs)) === 1 && !!(await dl1));
  await page.evaluate(() => closeSheet());
  await page.click('#rw-niyyah .dua'); await page.waitForTimeout(200);
  check('inline rite dua opens the full-screen reader', (await page.locator('#duaFocus.on').count()) === 1 && (await page.textContent('#dfAr')).length > 5 && (await page.locator('#dfNext').isHidden()));
  await page.click('#duaFocus button:has-text("Close")');

  console.log('Daily');
  await page.evaluate(() => { goTab('daily'); goSub('daily', 'today', true); }); await page.waitForTimeout(500);
  check('prayer grid 5 cells + next highlighted', (await page.locator('.pt').count()) === 5 && (await page.locator('.pt.next').count()) === 1);
  await page.click('#dw-fajr');
  check('daily tick + streak', (await page.textContent('#skFajrN')) === '1');
  await page.evaluate(() => goSub('daily', 'tools', true));
  for (let i = 0; i < 33; i++) await page.click('.tb-btn');
  check('tasbih cycle advances phrase', (await page.locator('.tb-chip.on').textContent()) === 'Alhamdulillah');
  await page.fill('#duaIn', 'Test dua'); await page.press('#duaIn', 'Enter'); await page.click('#duaList .tick');
  check('dua list add + tick', (await page.textContent('#duaList')).includes('1 of 1 asked'));
  await page.click('text=＋ cup');
  check('water counter', (await page.textContent('#waterLbl')).startsWith('1 of 8'));
  await page.evaluate(() => startQibla()); await page.waitForTimeout(800);
  check('qibla bearing computed', /\d+°/.test(await page.textContent('#qbDeg')));
  await page.evaluate(() => goSub('daily', 'stats', true));
  await page.click('text=Share my progress card'); await page.waitForTimeout(300);
  const dl2 = page.waitForEvent('download', { timeout: 6000 }).catch(() => null);
  await page.click('#gSheet button:has-text("Download")');
  check('progress card downloads', !!(await dl2));
  await page.evaluate(() => closeSheet());

  console.log('Places');
  await page.evaluate(() => goTab('places'));
  check('51 places', (await page.locator('.place').count()) === 51);
  check('tour card with 12 stops', (await page.locator('.stopchip').count()) === 12);
  await page.click('text=Set hotel here'); await page.waitForTimeout(500);
  check('distance chips from hotel', (await page.locator('.distchip').count()) > 30);
  await page.click('text=Plan a ziyarah route for Makkah');
  check('route planner', (await page.locator('#route-makkah .lg').count()) === 8);
  await page.fill('#plSearch', 'quba');
  check('search', (await page.locator('.place').count()) >= 1 && (await page.locator('#pl-quba').count()) === 1);

  await page.evaluate(() => openPlace('taneem')); await page.waitForTimeout(400);
  check('openPlace resets the search, opens the card and offers Umrah steps', (await page.inputValue('#plSearch')) === '' && (await page.locator('#pl-taneem.open').count()) === 1 && (await page.locator('#pl-taneem button:has-text("Umrah steps")').count()) === 1);

  console.log('More');
  await page.evaluate(() => { goTab('more'); goSub('more', 'duas', true); });
  check('8 duas with audio buttons', (await page.locator('.duacard').count()) === 8 && (await page.locator('.duacard .say').count()) === 8);
  await page.click('.duacard >> nth=3 >> .dua'); await page.waitForTimeout(200);
  check('dua reader opens with prev/next', (await page.locator('#duaFocus.on').count()) === 1 && (await page.textContent('#dfTitle')).includes('Yamani') && (await page.locator('#dfNext').isVisible()));
  await page.click('#dfNext');
  check('dua reader navigates', (await page.textContent('#dfTitle')).includes('Safa'));
  await page.click('#duaFocus button:has-text("Close")');
  check('More segment is now After · Duas · Settings', (await page.textContent('.seg[data-tab="more"]')).includes('After') && (await page.locator('#sub-more-guide .acc').count()) === 0);
  await page.evaluate(() => goSub('more', 'guide', true));
  await page.click('#postSw');
  check('post-umrah 90 habit chips', (await page.locator('.pchip').count()) === 90);
  check('journey chip goes to post card', (await page.textContent('#jChip')).includes('Post-Umrah'));
  await page.evaluate(() => goSub('more', 'settings', true));
  check('about card: version + correction mailto + links', (await page.textContent('#verLbl')) === (await page.evaluate(() => APP_VERSION)) && (await page.locator('#aboutCard a[href^="mailto:"]').count()) === 1 && (await page.locator('#sub-more-settings .res').count()) === 8);
  await page.click('#textSeg button:has-text("Large")');
  check('large text mode applies', (await page.getAttribute('html', 'data-text')) === 'lg' && (await page.evaluate(() => getComputedStyle(document.body).fontSize)) === '17px');
  await page.click('#textSeg button:has-text("Normal")');
  await page.click('button:has-text("▦ QR")');
  check('QR overlay with static SVG', (await page.locator('#qrShow.on .qr-box svg path').count()) === 1 && (await page.textContent('#qrShow')).includes('umrah-strivers.vercel.app'));
  await page.evaluate(() => document.getElementById('qrShow').classList.remove('on'));
  const bk = await page.evaluate(() => { const ls = {}; for (let i = 0; i < localStorage.length; i++) { const k = localStorage.key(i); if (k.indexOf('us-') === 0 && k !== 'us-ptcache' && k !== 'us-remlast') ls[k] = 1; } return Object.keys(ls).length; });
  check('backup covers every us- key', bk >= 8);
  await page.click('button:has-text("Reset everything")');
  check('reset is a two-step sheet', (await page.locator('#gSheet.on button:has-text("Export backup first")').count()) === 1);
  await page.evaluate(() => closeSheet());

  console.log('Deep links & a11y');
  await page.evaluate(() => goTab('daily', 'tools', 'tbCard')); await page.waitForTimeout(900);
  check('goTab(tab,sub,anchor) lands on the sub-tab and scrolls to the card', (await page.locator('#sub-daily-tools.on').count()) === 1 && (await page.evaluate(() => Math.abs(document.getElementById('tbCard').getBoundingClientRect().top - 118) < 40)) && (await page.getAttribute('.nav button[data-v="daily"]', 'aria-current')) === 'page');
  check('checklist rows are checkboxes; tapring is a labelled button', (await page.getAttribute('#dw-fajr', 'role')) === 'checkbox' && (await page.getAttribute('#dw-fajr', 'aria-checked')) === 'true' && (await page.getAttribute('#tawafRingBtn', 'aria-label')).includes('0 of 7'));
  await page.evaluate(() => goTab('daily', 'today')); await page.waitForTimeout(200);
  await page.focus('#dw-dhuhr'); await page.keyboard.press('Enter');
  check('keyboard Enter toggles a row', (await page.getAttribute('#dw-dhuhr', 'aria-checked')) === 'true');
  check('cross-reference chips render on checklist items', (await page.locator('#pw-rawdah .xchip').count()) === 1 && (await page.locator('#dw-ziyarah .xchip').count()) === 1 && (await page.locator('#itinArea .pl-link').count()) > 3);
  check('viewport allows pinch zoom', !(await page.getAttribute('meta[name="viewport"]', 'content')).includes('user-scalable=no'));

  console.log('Persistence');
  await page.reload(); await page.waitForTimeout(700);
  check('state survives reload', (await page.evaluate(() => ST.umrahs)) === 1 && (await page.evaluate(() => JSON.parse(localStorage.getItem('us-plan')).passport)) === true);

  console.log('Group setup link');
  const gHash = '#g=' + Buffer.from(encodeURIComponent(JSON.stringify({ by: 'Farhan', dep: '2030-10-12', tripLen: 12, itin: { first: 'madinah', mad: 4 }, city: 'Madinah', hotelInfo: { n: 'Hilton Makkah' } }))).toString('base64');
  await page.goto('about:blank'); await page.goto(URL + gHash); await page.waitForTimeout(900);
  check('group link opens the Apply sheet and strips the hash', (await page.textContent('#gSheetBody')).includes('Farhan') && (await page.evaluate(() => location.hash)) === '');
  await page.click('#gSheetBody button:has-text("Apply")'); await page.waitForTimeout(600);
  check('apply copies trip settings only', (await page.evaluate(() => ST.dep === '2030-10-12' && ST.tripLen === 12 && ST.itin.first === 'madinah' && ST.hotelInfo.n === 'Hilton Makkah' && ST.umrahs === 1 && JSON.parse(localStorage.getItem('us-plan')).passport === true)));
  check('no JS errors', errors.length === 0, errors);
  await browser.close();
  console.log(failed ? `\n${failed} check(s) FAILED` : '\nAll checks passed');
  process.exit(failed ? 1 : 0);
})().catch(e => { console.error('FATAL', e); process.exit(1); });
