/* Umrah Strivers smoke tests — run: npm test  (needs Chromium; set CHROME=/path/to/chromium if not auto-detected) */
const path = require('path');
const { chromium } = require('playwright-core');
const URL = 'file://' + path.resolve(__dirname, '../index.html');
const exe = process.env.CHROME || process.env.PLAYWRIGHT_CHROMIUM || (process.env.PLAYWRIGHT_BROWSERS_PATH ? process.env.PLAYWRIGHT_BROWSERS_PATH + '/chromium' : undefined);
const PT = { data: { timings: { Fajr: '05:12', Dhuhr: '12:21', Asr: '15:42', Maghrib: '18:33', Isha: '20:03' }, date: { hijri: { day: '24', month: { en: 'Rabi al-Awwal' }, year: '1448' } } } };
let failed = 0;
function check(name, cond, extra) { console.log((cond ? '  ✓ ' : '  ✗ ') + name + (cond ? '' : '  ' + JSON.stringify(extra || ''))); if (!cond) failed++; }

(async () => {
  const browser = await chromium.launch({ executablePath: exe });
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, geolocation: { latitude: 21.42, longitude: 39.83 }, permissions: ['geolocation'] });
  const page = await ctx.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', d => d.accept());
  // calendarByCity (the app fetches whole months) → one row per day of the requested month; anything else → the single-day shape
  await page.route('**/api.aladhan.com/**', r => { const m = /month=(\d+)&year=(\d+)/.exec(r.request().url()); let body = PT;
    if (m) { const days = new Date(+m[2], +m[1], 0).getDate(); body = { code: 200, data: Array.from({ length: days }, (_, i) => ({ timings: Object.assign({ Sunrise: '06:20 (+03)' }, PT.data.timings), date: { gregorian: { date: String(i + 1).padStart(2, '0') + '-' + String(m[1]).padStart(2, '0') + '-' + m[2] }, hijri: PT.data.date.hijri } })) }; }
    r.fulfill({ contentType: 'application/json', headers: { 'access-control-allow-origin': '*' }, body: JSON.stringify(body) }); });
  await page.goto(URL);
  await page.evaluate(() => localStorage.setItem('us-settings', JSON.stringify({ onboarded: true, name: 'Test', dep: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10), tripLen: 10, day: 1 })));
  await page.reload(); await page.waitForTimeout(900);

  console.log('Home');
  check('opens on Home', (await page.getAttribute('.view.on', 'id')) === 'view-home');
  check('journey chip counts down + no update chip', (await page.textContent('#jChip')).includes('day') && (await page.locator('#updChip').isHidden()));
  check('explains the app + greets by name', (await page.textContent('.hhero h2')).includes('Umrah companion') && (await page.textContent('.hs-t')).includes('Test') && (await page.locator('.stage').count()) === 5);
  check('next prayer loaded', (await page.textContent('#hNext')).includes('in '));
  check('9 quick actions + the wide Hotel / SOS row', (await page.locator('.qa').count()) === 10 && (await page.locator('.qa.wide').count()) === 1);
  await page.evaluate(() => { goTab('daily'); goSub('daily', 'stats', true); });
  check('empty stats point to Today and hold the share card back', (await page.locator('#stEmpty:visible').count()) === 1 && (await page.isDisabled('#shareBtn')) && (await page.textContent('#shareBtn')).includes('unlocks') && (await page.locator('#bdgGrid .bdg.no .mini').count()) === 9 && (await page.textContent('#bdgGrid .bdg >> nth=4')).includes('0/8'));
  await page.click('#bdgGrid .bdg >> nth=4');
  check('tapping a locked badge reveals how to earn it', (await page.locator('#bdgGrid .bdg.open .how:visible').count()) === 1 && (await page.textContent('#bdgGrid .bdg.open .how')).includes('8 places'));
  await page.evaluate(() => goTab('home'));

  console.log('Plan');
  await page.evaluate(() => { goTab('plan'); goSub('plan', 'prep', true); });
  await page.click('#pw-passport');
  check('checklist ticks', (await page.locator('#pw-passport.done').count()) === 1);
  check('itinerary renders 10 days', (await page.locator('.it').count()) === 10);
  check('timeline: blocking items first, capped groups, neutral late pills', (await page.textContent('#tlArea')).includes('Should already be done') && (await page.locator('.tli-more').count()) >= 1 && (await page.locator('.tli-when.over').count()) <= 5 && (await page.locator('#prepJumps button').count()) === 7);
  await page.click('.tli >> nth=0'); await page.waitForTimeout(600);
  const tickedBefore = await page.evaluate(() => Object.keys(planChk).filter(k => planChk[k]).length);
  await page.click('.toast.act button:has-text("Undo")'); await page.waitForTimeout(200);
  check('timeline tick offers Undo', tickedBefore === 2 && (await page.evaluate(() => Object.keys(planChk).filter(k => planChk[k]).length)) === 1);
  await page.evaluate(() => setProfile('w'));
  check('sister profile hides men-only rows and adds sisters\u2019 items', (await page.locator('#pw-ihram').count()) === 0 && (await page.locator('#pw-scissors').count()) === 1 && (await page.locator('#rw-cut').count()) === 0 && (await page.locator('#rw-cutw').count()) === 1);
  await page.evaluate(() => { setProfile(''); togKids(); });
  check('children toggle adds a 5th checklist + tile', (await page.locator('#sec-kids .row').count()) === 8 && (await page.locator('#catTiles .st').count()) === 5);
  await page.evaluate(() => togKids());
  await page.fill('#hName', 'Swiss\u00f4tel Makkah'); await page.fill('#hLead', 'Ahmed \u00b7 +966 55 123 4567'); await page.dispatchEvent('#hLead', 'change');
  await page.evaluate(() => showLost()); await page.waitForTimeout(200);
  check('I\u2019m lost overlay: leader tel link + 911/1966', (await page.locator('#lost.on .lost-tel[href="tel:+966551234567"]').count()) === 1 && (await page.locator('#lost a[href="tel:911"]').count()) === 1 && (await page.locator('#lost a[href="tel:1966"]').count()) === 1);
  await page.evaluate(() => { closeLost(); showDriver(); });
  check('driver card has Call + Maps actions', (await page.locator('#driver.on #drvActs a[href^="https://www.google.com/maps/dir/"]').count()) === 1);
  await page.evaluate(() => closeDriver());
  await page.evaluate(() => goSub('plan', 'learn', true));
  check('knowledge accordions', (await page.locator('#histCard .acc').count()) >= 9 && (await page.locator('#qaContainer .acc').count()) === 14 && (await page.locator('#scamContainer .acc').count()) === 10);
  check('Learn order: rites index first, essentials next, sisters section, quiz hand-off last', (await page.locator('#riteTiles .rtile').count()) === 4 && (await page.evaluate(() => { const ids = [...document.querySelectorAll('#sub-plan-learn > .card')].map(e => e.id); return ids.indexOf('ritesCard') === 0 && ids.indexOf('knowCard') === 1 && ids.indexOf('knowCard') < ids.indexOf('qaCard') && ids.indexOf('sisCard') > ids.indexOf('madCard') && ids.indexOf('lnQuizCard') === ids.length - 1; })) && (await page.locator('#sisContainer .acc').count()) === 7 && (await page.textContent('#lnQuizSub')).includes('Level 1') && (await page.locator('#knowCard .lnm').count()) === 1);
  await page.click('#knowContainer .acc >> nth=1 >> .acc-h');
  await page.click('#knowContainer .acc >> nth=1 >> .acc-b');
  check('accordion: header toggles, body tap does not collapse', (await page.locator('#knowContainer .acc.open').count()) === 1 && (await page.getAttribute('#knowContainer .acc >> nth=1 >> .acc-h', 'aria-expanded')) === 'true');
  await page.fill('#lnSearch', 'zamzam'); await page.dispatchEvent('#lnSearch', 'input'); await page.waitForTimeout(150);
  const lnHits = await page.evaluate(() => [...document.querySelectorAll('#sub-plan-learn .acc')].filter(a => !a.hidden).length);
  check('Learn search filters topics and hides empty cards', lnHits > 0 && lnHits < 20 && (await page.evaluate(() => document.getElementById('ritesCard').classList.contains('ln-hide') && document.getElementById('scamCard').classList.contains('ln-hide'))));
  await page.fill('#lnSearch', ''); await page.dispatchEvent('#lnSearch', 'input');
  check('flashcards: first session offers 5 cards', (await page.textContent('#fcArea')).includes('Start with 5 cards') && (await page.textContent('#fcDueLbl')).includes('ready'));
  await page.click('#fcArea .btn'); await page.waitForTimeout(100);
  check('flashcard grading hidden until revealed', (await page.locator('#fcWrap .fc-acts').isHidden()) && (await page.locator('.fc-end').count()) === 1);
  await page.click('#fcFlip'); await page.waitForTimeout(150);
  check('flip reveals grading; departure within 28 days puts Know-before-you-go first', (await page.locator('#fcWrap.flip .fc-acts').isVisible()) && (await page.textContent('#fcWrap .fc-src')).includes('Know before you go'));
  await page.click('#fcWrap .good');
  check('graded card stored under a string key', (await page.evaluate(() => Object.keys(JSON.parse(localStorage.getItem('us-cards')))[0])) === 'know0');
  await page.evaluate(() => { fcQueue = ['l0q0']; fcIdx = 0; renderFC(); fcFlip(); });
  check('quiz-derived card shows the options with the correct one marked', (await page.locator('#fcWrap .fc-opts div').count()) === 4 && (await page.locator('#fcWrap .fc-opts div.ok').count()) === 1);
  await page.evaluate(() => fcEnd());
  await page.evaluate(() => goSub('plan', 'quiz', true));
  check('7 quiz levels, 6 locked', (await page.locator('.lvl').count()) === 7 && (await page.locator('.lvl.locked').count()) === 6);
  check('kids corner first and collapsed, with 5 stories; quiz CTA + pass marks', (await page.evaluate(() => [...document.querySelectorAll('#sub-plan-quiz > .card')].map(e => e.id)[0])) === 'kidsCard' && (await page.locator('#kidsArea').isHidden()) && (await page.locator('#storyList .acc').count()) === 5 && (await page.textContent('.qz-cta')).includes('Level 1') && (await page.textContent('.lvl >> nth=0')).includes('pass = 8 correct') && (await page.locator('.lvl.next').count()) === 1 && (await page.textContent('#qzBest')) === '0/7');
  await page.click('.lvl >> nth=1');
  check('locked level shows the lock card', (await page.locator('.qz-lock').count()) === 1 && (await page.textContent('.qz-lock')).includes('8 of 10 correct'));
  await page.click('.qz-lock button:has-text("Unlock all levels")');
  check('unlock all opens every level; restore re-locks', (await page.locator('.lvl.locked').count()) === 0 && (await page.textContent('.qz-free')).includes('Restore') && (await page.evaluate(() => { qzFree(false); return document.querySelectorAll('.lvl.locked').length; })) === 6);
  await page.click('.lvl >> nth=0');
  check('question header shows the pass mark', (await page.textContent('.qz-needrow')).includes('8 more to pass') && (await page.textContent('.qz-top')).includes('Q1/10'));
  const n1 = await page.evaluate(() => QUIZ_LEVELS[0].qs.length);
  const pick = async () => { const c = await page.evaluate(() => qzPerm.indexOf(qzAns(curQ()))); await page.click('#qzo-' + c); await page.click('#qzFb .btn'); };
  for (let k = 0; k < 2; k++) await pick();
  await page.evaluate(() => qzExit());
  check('exit keeps a resume row at the next unanswered question', (await page.locator('.qz-resume').count()) === 1 && (await page.textContent('.qz-resume')).includes('Q3/10') && (await page.evaluate(() => JSON.parse(localStorage.getItem('us-quiz')).cur.i)) === 2);
  await page.click('.qz-resume .btn');
  check('resume restores the score and position', (await page.textContent('.qz-top')).includes('Q3/10') && (await page.textContent('.qz-top')).includes('2 ✓'));
  for (let k = 2; k < n1; k++) await pick();
  check('level 1 passed at 100%; pass screen starts the next level', (await page.textContent('.qz-final .big')) === '100%' && (await page.textContent('.qz-final .btn.gold')).includes('Ihram') && (await page.locator('.qz-final button:has-text("Retake")').count()) === 0);
  await page.click('text=← All levels');
  check('level 2 unlocked', (await page.locator('.lvl.locked').count()) === 5 && (await page.locator('.qz-resume').count()) === 0);
  await page.click('.lvl >> nth=1');
  await page.evaluate(() => togPlan('visa'));
  check('checklist updates do not wipe a running level', (await page.locator('.qz-top').count()) === 1 && (await page.evaluate(() => qzActive)));
  await page.evaluate(() => { togPlan('visa'); qzExit(); startKids(); });
  check('kids quiz: 3 big options, read-aloud and Done', (await page.locator('#kidsArea .kq-o').count()) === 3 && (await page.locator('#kidsArea .kq-say').count()) === 1 && (await page.locator('#kidsStart').isHidden()));
  await page.evaluate(() => kidsDone());
  check('kids Done restores the Start row', (await page.locator('#kidsArea').isHidden()) && (await page.locator('#kidsStart').isVisible()));

  console.log('Umrah');
  await page.evaluate(() => goTab('umrah')); await page.waitForTimeout(300);
  check('before departure the Umrah tab defaults to Steps, with the you-are-here strip on step 1', (await page.evaluate(() => ST.sub.umrah)) === 'steps' && (await page.locator('#sub-umrah-steps.on').count()) === 1 && (await page.textContent('#riteNow')).includes('Now · step 1 of 17') && (await page.locator('#riteNow .now-tick').count()) === 1);
  await page.evaluate(() => goSub('umrah', 'count', true));
  check('counters open: live hero, sa\u2019i card compact, tip for round 1, dua under the ring', (await page.textContent('#riteHeroT')) === 'Ready to begin' && (await page.locator('#saiCard.compact').count()) === 1 && (await page.locator('#tawafCard.compact').count()) === 0 && (await page.textContent('#tawafTip')).includes('Now: round 1 of 7') && (await page.locator('#tawafDua .dua .ar').count()) === 1);
  await page.click('#tawafRingBtn');
  check('wudu gate is a sheet (no confirm) and blocks the count', (await page.locator('#gSheet.on button:has-text("Yes, I have wudu")').count()) === 1 && (await page.textContent('#tawafN')) === '0');
  await page.click('#gSheet button:has-text("Yes, I have wudu")'); await page.waitForTimeout(100);
  check('confirming wudu counts round 1, stamps the time, tip moves to round 2', (await page.textContent('#tawafN')) === '1' && (await page.evaluate(() => !!ST.wudu && !!ST.wuduAt)) && (await page.textContent('#wuduSt')).includes('Wudu made') && (await page.textContent('#tawafTip')).includes('Now: round 2 of 7') && (await page.textContent('#riteHeroT')).includes('round 2 of 7'));
  await page.click('#tawafRingBtn');
  check('a second tap within 800 ms is ignored', (await page.textContent('#tawafN')) === '1');
  for (let i = 1; i < 7; i++) { await page.evaluate(() => { lastTap.tawaf = 0; }); await page.click('#tawafRingBtn'); }
  check('tawaf counter reaches 7, ticks the rites step and shows the hand-off strip', (await page.textContent('#tawafN')) === '7' && await page.isVisible('#tawafDone') && (await page.evaluate(() => riteChk.rounds === true)) && (await page.locator('#tawafDone .brg').count()) === 3 && (await page.textContent('#riteHeroT')).includes('Sa\u2019i'));
  await page.click('#tawafDone .brg >> nth=0');
  check('hand-off tick rows drive the rites checklist', (await page.evaluate(() => riteChk.maqam === true)) && (await page.locator('#rw-maqam.done').count()) === 1);
  await page.waitForTimeout(1400);
  await page.click('#tawafDone button:has-text("Start Sa")'); await page.waitForTimeout(500);
  check('Start Sa\u2019i makes sa\u2019i the one big ring; sa\u2019i tip names the hill', (await page.locator('#saiCard.compact').count()) === 0 && (await page.locator('#tawafCard.compact').count()) === 1 && (await page.textContent('#saiTip')).includes('On Safa \u2192 walk to Marwah'));
  await page.evaluate(() => { togRite('niyyah'); for (let i = 0; i < 7; i++) { lastTap.sai = 0; cntr('sai', 1); } });
  check('sa\u2019i done points to halq before cutting', (await page.textContent('#saiDone')).includes('halq') && (await page.locator('#saiDone button:has-text("Record this Umrah")').count()) === 0 && (await page.textContent('#saiTip')).includes('Finished on Marwah'));
  await page.evaluate(() => togRite('cut'));
  check('timeline stamped + Record button appears after cutting', (await page.locator('#logArea .lg.on').count()) === 6 && (await page.locator('#saiDone button:has-text("Record this Umrah")').count()) === 1 && (await page.textContent('#riteHeroT')).includes('Taqabbal'));
  await page.evaluate(() => togRite('niyyah'));
  check('un-ticking the intention removes its stamp', (await page.evaluate(() => ST.log.ihram === undefined)) && (await page.locator('#logArea .lg.on').count()) === 5);
  await page.evaluate(() => togRite('niyyah'));
  check('the first counted round ticked wudu + the Black Stone start', (await page.evaluate(() => riteChk.start === true && riteChk.wudu === true)));
  await page.waitForTimeout(1400);
  await page.click('#saiCard button:has-text("Big counter")');
  check('big counter opens with the dua strip and a completion panel at 7', (await page.locator('#focus.on').count()) === 1 && (await page.locator('#focusDua .ar').count()) === 1 && (await page.locator('#focusDone').isVisible()) && (await page.textContent('#focusDone')).includes('halq'));
  await page.click('#focus .focus-top button:has-text("Exit")');
  await page.evaluate(() => cntrReset('sai'));
  check('counter reset asks first (sheet)', (await page.locator('#gSheet.on button:has-text("Reset to 0")').count()) === 1 && (await page.evaluate(() => ST.sai)) === 7);
  await page.evaluate(() => closeSheet());
  await page.click('.sis-line');
  check('period line opens the ruling sheet', (await page.textContent('#gSheetBody')).includes('Bukhari 305'));
  await page.evaluate(() => closeSheet());
  await page.evaluate(() => goSub('umrah', 'steps', true));
  await page.click('#rw-ghusl .why');
  check('why explainer toggles', (await page.locator('#rw-ghusl .whyb.on').count()) === 1);
  check('rites step carries the live counter chip', (await page.textContent('#live-rounds')).includes('7 / 7 rounds'));
  check('story chips on ihram, Black Stone and Safa steps', (await page.locator('#rw-garb .xchip').count()) === 1 && (await page.locator('#rw-start .xchip').count()) === 1 && (await page.locator('#rw-safa .xchip').count()) === 1);
  check('phase chips use global numbering; mataf map sits inside Phase 2; trouble panel has 8 rows', (await page.textContent('#sp-ph4')) === '✓ done' && (await page.textContent('#sp-ph3')) === '1/3' && (await page.locator('#sec-ph2 #matafSec').count()) === 1 && (await page.locator('#sub-umrah-steps > #matafSec').count()) === 0 && (await page.locator('#sec-trouble .acc').count()) === 8);
  check('steps follow the physical order and carry every recitation', (await page.evaluate(() => { const ids = [...document.querySelectorAll('#riteContainer .stp')].map(e => e.id); return ids.indexOf('rw-yamani') < ids.indexOf('rw-rounds') && ids.indexOf('rw-marwah') < ids.indexOf('rw-laps') && ids.indexOf('rw-done') < 0; })) && (await page.locator('#rw-safa .dua').count()) === 2 && (await page.locator('#rw-start .dua').count()) === 1 && (await page.locator('#rw-zamzam .dua').count()) === 1 && (await page.locator('#rw-niyyah .dua.duaopt').count()) === 1 && (await page.locator('#sec-ph1 .callout').count()) === 1 && (await page.locator('#rw-yamani .rep').count()) === 1);
  await page.evaluate(() => startWalk()); await page.waitForTimeout(150);
  check('walkthrough opens at the first unticked step', (await page.locator('#walk.on').count()) === 1 && (await page.textContent('#walkHd')).includes('Step 1 of 17') && (await page.textContent('#walkNext')).includes('Done'));
  await page.click('#walkNext'); await page.waitForTimeout(100);
  check('Done → Next ticks the step and advances', (await page.evaluate(() => riteChk.ghusl === true)) && (await page.textContent('#walkHd')).includes('Step 2 of 17'));
  await page.evaluate(() => closeWalk()); await page.waitForTimeout(100);
  await page.evaluate(() => buildPrint());
  check('print sheet lists the rites, duas and packing', (await page.locator('#printSheet h2').count()) >= 6 && (await page.locator('#printSheet .pr-dua').count()) >= 8 && (await page.locator('#printSheet .pr-pack li').count()) > 8);
  check('completion block is ready after cutting', (await page.locator('#riteDone.ready #recordBtn').count()) === 1 && (await page.locator('#sub-umrah-steps > .btn.gold').count()) === 0);
  await page.evaluate(() => setSecOpen('ph4', true)); await page.waitForTimeout(450);
  await page.click('#recordBtn'); await page.waitForTimeout(300);
  check('recording leaves a keepsake + log-today note in the completion block', (await page.textContent('#riteDoneNote')).includes('Keepsake') && (await page.locator('#riteDoneNote button:has-text("Log today")').count()) === 1);
  await page.evaluate(() => goSub('umrah', 'steps', true)); await page.click('#umrahsArea .chip-btn'); await page.waitForTimeout(300);
  check('keepsake opens the export sheet with preview', (await page.locator('#gSheet.on img').count()) === 1);
  const dl1 = page.waitForEvent('download', { timeout: 6000 }).catch(() => null);
  await page.click('#gSheet button:has-text("Download")');
  check('umrah recorded + keepsake downloads', (await page.evaluate(() => ST.umrahs)) === 1 && !!(await dl1));
  await page.evaluate(() => closeSheet());
  await page.evaluate(() => { goSub('umrah', 'count', true); ST.wudu = true; saveST(); updWudu(); for (let i = 0; i < 7; i++) { lastTap.tawaf = 0; cntr('tawaf', 1); } });
  check('after recording, the counter is in nafl mode: no stamps, inline log button', (await page.evaluate(() => ST.tmode)) === 'nafl' && (await page.evaluate(() => Object.keys(ST.log || {}).length)) === 0 && (await page.locator('#tawafDone button:has-text("Log nafl tawaf #1")').count()) === 1);
  await page.click('#tawafDone button:has-text("Log nafl tawaf")');
  check('nafl tawaf logged to today, counter reset, wudu kept', (await page.evaluate(() => dailyChk.d1.ntawaf === true && dailyChk.d1.ntawafN === 1 && ST.tawaf === 0 && ST.wudu === true)));
  await page.evaluate(() => goSub('umrah', 'steps', true));
  await page.click('#rw-talb .dua'); await page.waitForTimeout(200);
  check('inline rite dua opens the full-screen reader', (await page.locator('#duaFocus.on').count()) === 1 && (await page.textContent('#dfAr')).length > 5 && (await page.locator('#dfNext').isHidden()));
  await page.click('#duaFocus button:has-text("Close")');
  await page.click('#rw-niyyah .dua.duaopt'); await page.waitForTimeout(200);
  check('a step with two duas opens the reader on the tapped one with ◀ ▶', (await page.textContent('#dfTitle')).includes('optional') && (await page.locator('#dfPrev').isVisible()));
  await page.click('#duaFocus button:has-text("Close")');
  await page.evaluate(() => startFresh());
  check('Start fresh asks first', (await page.locator('#gSheet.on button:has-text("nothing recorded")').count()) === 1);
  await page.click('#gSheet button:has-text("nothing recorded")'); await page.waitForTimeout(100);
  check('Start fresh clears ticks, counters and timeline without recording', (await page.evaluate(() => Object.keys(riteChk).length === 0 && Object.keys(ST.log).length === 0 && ST.umrahs === 1)));
  await page.evaluate(() => { goSub('umrah', 'count', true); ST.wudu = true; saveST(); updWudu(); });

  console.log('Daily');
  await page.evaluate(() => { goTab('daily'); goSub('daily', 'today', true); }); await page.waitForTimeout(500);
  check('prayer grid 5 cells + next highlighted', (await page.locator('.pt').count()) === 5 && (await page.locator('.pt.next').count()) === 1);
  check('day nav lives in the hero; prayer strip is collapsed with the next prayer, time and city; live Umm al-Qura note', (await page.locator('.dhero #dayNav #dayDisp').count()) === 1 && (await page.locator('#ptSec.shut').count()) === 1 && /in .*05:12|12:21|15:42|18:33|20:03/.test(await page.textContent('#ptNext')) && (await page.textContent('#ptNext')).includes('Makkah') && (await page.textContent('#ptNote')).includes('Umm al-Qura (') && (await page.textContent('#ptNote')).includes('Duha from ~06:35'));
  check('month cache holds both cities and the row order follows the day', (await page.evaluate(() => { const c = JSON.parse(localStorage.getItem('us-ptcache')); return Object.keys(c).filter(k => k.indexOf('Madinah|') === 0).length > 27 && !!c['_mMakkah|' + new Date().getFullYear() + '-' + (new Date().getMonth() + 1)]; })) && (await page.evaluate(() => [...document.querySelectorAll('#sec-salah .row')].map(e => e.id).join(',').indexOf('dw-tahajjud,dw-fajr,dw-madhkar,dw-duha,dw-dhuhr') === 0)));
  check('computed prayer times match the Umm al-Qura table for Makkah, 6 Sep (Fajr 04:48, Dhuhr 12:20, Maghrib 18:32, Isha +90) and Ramadan Isha is +120', (await page.evaluate(() => { const m = v => +v.split(':')[0] * 60 + +v.split(':')[1], r = computePT('Makkah', 2026, 8, 6), z = computePT('Makkah', 2026, 1, 20); return Math.abs(m(r.t.Fajr) - 288) <= 3 && Math.abs(m(r.t.Maghrib) - 1112) <= 3 && m(r.t.Isha) - m(r.t.Maghrib) === 90 && Math.abs(m(r.t.Dhuhr) - 740) <= 3 && r.s === '06:05' && m(z.t.Isha) - m(z.t.Maghrib) === 120; })));
  await page.click('#ptSec .sec-hd'); await page.waitForTimeout(500);
  check('tapping the strip opens the prayer panel', (await page.locator('#ptSec.shut').count()) === 0 && (await page.locator('#ptGrid').isVisible()));
  await page.click('#pt-Fajr'); await page.waitForTimeout(150);
  check('prayer tile ticks the salah row (and back); streak tile reads 1d', (await page.locator('#dw-fajr.done').count()) === 1 && (await page.locator('#pt-Fajr.done').count()) === 1 && (await page.textContent('#skFajrN')) === '1d' && (await page.locator('#sec-quran .apps').count()) === 1 && (await page.evaluate(() => { const b = document.querySelector('#sec-quran .sec-bd'); return b.lastElementChild.classList.contains('apps') && b.querySelector('.apps .applink').textContent.includes('Open'); })) && (await page.locator('#sec-dhikr .apps .applink >> nth=0').textContent()).includes('Tasbih') && (await page.locator('.pts').count()) === 0 && (await page.textContent('#dHeroS')).includes('of 25 completed'));
  await page.evaluate(() => { ST.dep = new Date(Date.now() - 3 * 86400000).toISOString().slice(0, 10); saveST(); syncDay(); });
  check('the day follows the departure date (Day 4), chip agrees, date line shows', (await page.evaluate(() => ST.day)) === 4 && (await page.evaluate(() => expectedDay())) === 4 && (await page.textContent('#jChip')).includes('Day 4') && (await page.textContent('#dayDate')).length > 8 && (await page.locator('#dayToday').isHidden()));
  await page.evaluate(() => changeDay(-1));
  check('manual ◀ shows past + a Today chip; ▶ at the last day is disabled', (await page.textContent('#dayDate')).includes('Past day') && (await page.locator('#dayToday').isVisible()) && (await page.evaluate(() => { setDay(ST.tripLen, true); return document.getElementById('dayNext').disabled && document.getElementById('dayTools').textContent.includes('Trip finished'); })));
  await page.evaluate(() => { goToday(); setExcused(true); });
  check('excused day: salah rows greyed and locked, quran still counts, streaks pause', (await page.locator('#dw-fajr.excused').count()) === 1 && (await page.locator('#dw-recite.excused').count()) === 0 && (await page.textContent('#dHeroS')).includes('that count today') && (await page.textContent('#dHeroS')).includes('Bukhari 305') && (await page.locator('#pt-Fajr.excused').count()) === 1 && (await page.evaluate(() => { togDaily('fajr'); return !dailyChk[dayKey()].fajr; })));
  await page.evaluate(() => { setExcused(false); ST.dep = new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10); ST.day = 1; saveST(); updDaily(); updChip(); });
  await page.evaluate(() => { ST.kidNames = ['Ali']; saveST(); renderKidsDay(); });
  for (let i = 0; i < 5; i++) await page.click('#kidsDay .kd-t >> nth=' + i);
  check('kids’ day: 5 tiles per child, 5/5 earns a star, stays out of the adult total', (await page.locator('#kidsDay .kd-t.on').count()) === 5 && (await page.textContent('#kidsDay .kd-name')).includes('⭐') && (await page.textContent('#dHeroS')).includes('of 25'));
  await page.evaluate(() => { ST.kidNames = []; saveST(); renderKidsDay(); });
  await page.evaluate(() => { setMeet('Gate 79'); });
  check('meeting point echoes to Home’s prayer strip and the hotel card', (await page.textContent('#hNext')).includes('meet: Gate 79') && (await page.inputValue('#hMeet')) === 'Gate 79');
  await page.evaluate(() => goSub('daily', 'tools', true));
  check('tools: jump chips + pre-trip order (duas first) + collapsible dua section', (await page.locator('.tooljumps .pill').count()) === 4 && (await page.evaluate(() => getComputedStyle(document.getElementById('duaCard')).order)) === '1' && (await page.evaluate(() => getComputedStyle(document.getElementById('tbCard')).order)) === '3' && (await page.locator('#duaCard #sec-dualist:not(.shut)').count()) === 1 && (await page.locator('#duaList .dua-sug .chip-btn').count()) === 8);
  for (let i = 0; i < 33; i++) await page.click('.tb-btn');
  check('tasbih cycle advances phrase', (await page.locator('.tb-chip.on').textContent()) === 'Alhamdulillah');
  check('tasbih: 5 targets, 34 auto-set for Allahu Akbar comes next, cycle persisted', (await page.locator('#tbTargets .tb-tg').count()) === 5 && (await page.evaluate(() => tbTargetN)) === 33 && (await page.evaluate(() => { const t = JSON.parse(localStorage.getItem('us-tasbih')); return t._cur && t._cur.p === 1 && t._cur.c === 0 && t.d1 === 33; })));
  await page.click('.tb-btn'); await page.click('.tb-btn'); await page.click('.tb-meta button:has-text("−1")');
  check('tasbih −1 undoes a mis-tap (cycle and day total)', (await page.textContent('#tbN')) === '1' && (await page.textContent('#tbToday')) === '34');
  await page.click('#tbTargets .tb-tg >> nth=2'); for (let i = 0; i < 4; i++) await page.click('.tb-btn');
  await page.evaluate(() => { tbCount = 99; renderTB(); }); await page.click('.tb-btn'); await page.click('.tb-btn');
  check('a 100 target keeps counting past 100 on the same phrase', (await page.textContent('#tbN')) === '101' && (await page.locator('.tb-chip.on').textContent()) === 'Alhamdulillah' && (await page.textContent('#tbOf')).includes('keep going'));
  await page.evaluate(() => { tbSet(0); tbSetTarget(33); });
  await page.click('.tb-meta button:has-text("Focus")');
  check('full-screen tasbih: title, target, Arabic, tap counts, undo', (await page.locator('#focus.on.tasbih').count()) === 1 && (await page.textContent('#focusTitle')).includes('SubhanAllah') && (await page.textContent('#focusOf')).includes('of 33') && (await page.locator('#focus.tasbih #focusWudu:visible').count()) === 0);
  await page.click('#focus .focus-tap'); await page.click('#focus .focus-tap'); await page.click('#focus .btn.undo');
  check('focus tasbih taps + undo feed the counter', (await page.textContent('#focusN')) === '1' && (await page.evaluate(() => tbCount)) === 1);
  await page.click('#focus .focus-top button:has-text("Exit")');
  await page.fill('#duaIn', 'Test dua'); await page.press('#duaIn', 'Enter'); await page.click('#duaList .tick');
  check('dua list add + tick', (await page.textContent('#duaList')).includes('1 of 1 asked') && (await page.textContent('#sp-dualist')) === '1/1 asked' && (await page.locator('#duaList button:has-text("new round")').count()) === 1);
  await page.click('#duaList button:has-text("new round")');
  check('new round unticks every dua', (await page.evaluate(() => duas.filter(d => d.done).length)) === 0 && (await page.textContent('#duaList')).includes('0 of 1 asked'));
  await page.click('#duaList button[aria-label^="Remove"]'); await page.waitForTimeout(100);
  const gone = await page.evaluate(() => duas.length);
  await page.click('.toast.act button:has-text("Undo")'); await page.waitForTimeout(150);
  check('deleting a dua offers Undo', gone === 0 && (await page.evaluate(() => duas.length === 1 && duas[0].t === 'Test dua')));
  await page.click('#duaList .tick');
  await page.click('text=＋ cup');
  check('water counter', (await page.textContent('#waterLbl')).startsWith('1 cup today') && (await page.locator('#waterCard #kmLbl').count()) === 0);
  await page.evaluate(() => startQibla()); await page.waitForTimeout(800);
  check('qibla bearing computed', /\d+°/.test(await page.textContent('#qbDeg')));
  check('compass button toggles to Stop and the copy says how to hold the phone', (await page.textContent('#qbBtn')).includes('Stop') && (await page.evaluate(() => qbActive)) && (await page.textContent('#qbStatus')).includes('Hold the phone flat'));
  await page.evaluate(() => goTab('home'));
  check('leaving Tools stops the compass', (await page.evaluate(() => qbActive)) === false && (await page.textContent('#qbBtn')).includes('Start'));
  await page.evaluate(() => goTab('daily'));
  await page.evaluate(() => goSub('daily', 'stats', true));
  check('trip stats carry the shared numbers (km, dhikr, duas, Fajr streak, cups) and the share button sits below achievements', (await page.textContent('#stKm')).includes('km') && (await page.textContent('#stDhikr')) === String(await page.evaluate(() => tbTotal())) && (await page.textContent('#stDuas')) === '1 of 1' && (await page.textContent('#stCups')) === '1' && /\d+ days?/.test(await page.textContent('#stFajr')) && (await page.locator('#stEmpty:visible').count()) === 0 && !(await page.isDisabled('#shareBtn')) && (await page.evaluate(() => document.getElementById('shareBtn').previousElementSibling.textContent.includes('Achievements'))));
  check('heatmap is a day picker with a legend', (await page.locator('#heatGrid .hc[role="button"]').count()) === 10 && (await page.locator('#heatLeg .hc').count()) === 4 && (await page.evaluate(() => getComputedStyle(document.getElementById('heatGrid')).gridTemplateColumns.split(' ').length)) === 7);
  await page.click('#heatGrid .hc >> nth=2'); await page.waitForTimeout(150);
  check('tapping a heat cell opens that day on Today', (await page.evaluate(() => ST.day)) === 3 && (await page.locator('#sub-daily-today.on').count()) === 1);
  await page.evaluate(() => { setDay(1, true); goSub('daily', 'stats', true); });
  await page.click('text=Share my progress card'); await page.waitForTimeout(300);
  const dl2 = page.waitForEvent('download', { timeout: 6000 }).catch(() => null);
  await page.click('#gSheet button:has-text("Download")');
  check('progress card downloads', !!(await dl2));
  await page.evaluate(() => closeSheet());

  console.log('Places');
  await page.evaluate(() => goTab('places'));
  check('51 places', (await page.locator('.place').count()) === 51);
  check('tour card with 12 stops', (await page.locator('.stopchip').count()) === 12);
  await page.click('text=Set hotel here'); await page.waitForTimeout(500);
  check('distance chips from hotel', (await page.locator('.distchip').count()) > 30);
  await page.click('text=Plan a ziyarah route for Makkah');
  check('route planner', (await page.locator('#route-makkah .lg').count()) === 8);
  await page.fill('#plSearch', 'quba');
  check('search', (await page.locator('.place').count()) >= 1 && (await page.locator('#pl-quba').count()) === 1);

  await page.evaluate(() => openPlace('taneem')); await page.waitForTimeout(400);
  check('openPlace resets the search, opens the card and offers Umrah steps', (await page.inputValue('#plSearch')) === '' && (await page.locator('#pl-taneem.open').count()) === 1 && (await page.locator('#pl-taneem button:has-text("Umrah steps")').count()) === 1);

  console.log('More');
  await page.evaluate(() => { goTab('more'); goSub('more', 'duas', true); });
  check('8 duas with audio buttons', (await page.locator('.duacard').count()) === 8 && (await page.locator('.duacard .say').count()) === 8);
  await page.click('.duacard >> nth=3 >> .dua'); await page.waitForTimeout(200);
  check('dua reader opens with prev/next', (await page.locator('#duaFocus.on').count()) === 1 && (await page.textContent('#dfTitle')).includes('Yamani') && (await page.locator('#dfNext').isVisible()));
  await page.click('#dfNext');
  check('dua reader navigates', (await page.textContent('#dfTitle')).includes('Safa'));
  await page.click('#duaFocus button:has-text("Close")');
  check('More segment is now After · Duas · Settings', (await page.textContent('.seg[data-tab="more"]')).includes('After') && (await page.locator('#sub-more-guide .acc').count()) === 0);
  await page.evaluate(() => goSub('more', 'guide', true));
  await page.click('#postSw');
  check('post-umrah 90 habit chips', (await page.locator('.pchip').count()) === 90);
  check('journey chip goes to post card', (await page.textContent('#jChip')).includes('Post-Umrah'));
  await page.evaluate(() => goSub('more', 'settings', true));
  check('about card: version + correction mailto + links', (await page.textContent('#verLbl')) === (await page.evaluate(() => APP_VERSION)) && (await page.locator('#aboutCard a[href^="mailto:"]').count()) === 1 && (await page.locator('#sub-more-settings .res').count()) === 8);
  check('achievements total follows the badge list (Little Pilgrim added)', (await page.textContent('#bdgTot')) === '9' && (await page.locator('#bdgGrid .bdg').count()) === 9);
  const dl3 = page.waitForEvent('download', { timeout: 6000 }).catch(() => null);
  await page.click('button:has-text("Add week")');
  check('week of prayer alerts exports as .ics with Riyadh TZID', !!(await dl3) && (await page.evaluate(() => { const B = buildICS('Makkah', 7); return B.n === 35 && B.ics.indexOf('DTSTART;TZID=Asia/Riyadh:') > -1 && B.ics.indexOf('TRIGGER:-PT20M') > -1 && B.ics.indexOf('SUMMARY:Fajr — Makkah') > -1; })) && (await page.locator('#sub-more-settings #remSw').count()) === 1);
  await page.click('#textSeg button:has-text("Large")');
  check('large text mode applies', (await page.getAttribute('html', 'data-text')) === 'lg' && (await page.evaluate(() => getComputedStyle(document.body).fontSize)) === '17px');
  await page.click('#textSeg button:has-text("Normal")');
  await page.click('button:has-text("▦ QR")');
  check('QR overlay with static SVG', (await page.locator('#qrShow.on .qr-box svg path').count()) === 1 && (await page.textContent('#qrShow')).includes('umrah-strivers.vercel.app'));
  await page.evaluate(() => document.getElementById('qrShow').classList.remove('on'));
  const bk = await page.evaluate(() => { const ls = {}; for (let i = 0; i < localStorage.length; i++) { const k = localStorage.key(i); if (k.indexOf('us-') === 0 && k !== 'us-ptcache' && k !== 'us-remlast') ls[k] = 1; } return Object.keys(ls).length; });
  check('backup covers every us- key', bk >= 8);
  await page.click('button:has-text("Reset everything")');
  check('reset is a two-step sheet', (await page.locator('#gSheet.on button:has-text("Export backup first")').count()) === 1);
  await page.evaluate(() => closeSheet());

  console.log('Deep links & a11y');
  await page.evaluate(() => goTab('daily', 'tools', 'tbCard')); await page.waitForTimeout(900);
  check('goTab(tab,sub,anchor) lands on the sub-tab and scrolls to the card', (await page.locator('#sub-daily-tools.on').count()) === 1 && (await page.evaluate(() => Math.abs(document.getElementById('tbCard').getBoundingClientRect().top - 118) < 40)) && (await page.getAttribute('.nav button[data-v="daily"]', 'aria-current')) === 'page');
  check('checklist rows are checkboxes; tapring is a labelled button', (await page.getAttribute('#dw-fajr', 'role')) === 'checkbox' && (await page.getAttribute('#dw-fajr', 'aria-checked')) === 'true' && (await page.getAttribute('#tawafRingBtn', 'aria-label')).includes('0 of 7'));
  await page.evaluate(() => goTab('daily', 'today')); await page.waitForTimeout(200);
  await page.focus('#dw-dhuhr'); await page.keyboard.press('Enter');
  check('keyboard Enter toggles a row', (await page.getAttribute('#dw-dhuhr', 'aria-checked')) === 'true');
  check('cross-reference chips render on checklist items', (await page.locator('#pw-rawdah .xchip').count()) === 1 && (await page.locator('#dw-ziyarah .xchip').count()) === 1 && (await page.locator('#itinArea .pl-link').count()) > 3);
  check('viewport allows pinch zoom', !(await page.getAttribute('meta[name="viewport"]', 'content')).includes('user-scalable=no'));

  console.log('Persistence');
  await page.reload(); await page.waitForTimeout(700);
  check('state survives reload', (await page.evaluate(() => ST.umrahs)) === 1 && (await page.evaluate(() => JSON.parse(localStorage.getItem('us-plan')).passport)) === true);

  console.log('Group setup link');
  const gHash = '#g=' + Buffer.from(encodeURIComponent(JSON.stringify({ by: 'Farhan', dep: '2030-10-12', tripLen: 12, itin: { first: 'madinah', mad: 4 }, city: 'Madinah', hotelInfo: { n: 'Hilton Makkah' } }))).toString('base64');
  await page.goto('about:blank'); await page.goto(URL + gHash); await page.waitForTimeout(900);
  check('group link opens the Apply sheet and strips the hash', (await page.textContent('#gSheetBody')).includes('Farhan') && (await page.evaluate(() => location.hash)) === '');
  await page.click('#gSheetBody button:has-text("Apply")'); await page.waitForTimeout(600);
  check('apply copies trip settings only', (await page.evaluate(() => ST.dep === '2030-10-12' && ST.tripLen === 12 && ST.itin.first === 'madinah' && ST.hotelInfo.n === 'Hilton Makkah' && ST.umrahs === 1 && JSON.parse(localStorage.getItem('us-plan')).passport === true)));
  check('no JS errors', errors.length === 0, errors);
  await browser.close();
  console.log(failed ? `\n${failed} check(s) FAILED` : '\nAll checks passed');
  process.exit(failed ? 1 : 0);
})().catch(e => { console.error('FATAL', e); process.exit(1); });
