/* Umrah Strivers — content & data (edit here to change text, places, quiz, duas) */
/* ════════════════════════ DATA ════════════════════════ */
var QUOTES=[
'"Perform Umrah after Umrah, for the two of them wipe away whatever sins came between them." — Bukhari 1773',
'"They will come to you on foot and on every lean camel from every distant pass." — Quran 22:27',
'"The guests of Allah are three: the warrior, the Hajj pilgrim, and the Umrah pilgrim." — Nasai 2625',
'"Perform Umrah in Ramadan, for an Umrah in Ramadan is equal to a Hajj." — Bukhari 1863',
'"Whoever comes to this House and does not speak obscenely or act wickedly returns as the day his mother bore him." — Muslim 1350'
];

var PLAN=[
{id:'docs',ico:'🛂',title:'Documents & bookings',items:[
{id:'passport',wk:12,label:'Passport valid 6+ months',exp:'Saudi Arabia requires at least six months of validity from arrival.'},
{id:'visa',wk:6,label:'Umrah visa / eVisa obtained (Nusuk)',exp:'Apply via the official Nusuk platform or an authorised agent — beware of unofficial sites.'},
{id:'flights',wk:8,label:'Flights booked',exp:'Jeddah (JED) for Makkah first, or Madinah (MED) if starting in Madinah.'},
{id:'hotels',wk:8,label:'Hotels booked (near the Haram if possible)',exp:'Proximity means more prayers in congregation — worth every riyal.'},
{id:'nusuk',wk:4,label:'Nusuk app installed & account created',exp:'Needed for Rawdah permits in Madinah and official services.'},
{id:'rawdah',wk:3,label:'Rawdah permit booked on Nusuk',exp:'Visiting the Rawdah in Masjid an-Nabawi requires a free timed permit — book early.'},
{id:'insurance',wk:4,label:'Travel insurance arranged',exp:'Often included with the Umrah visa — confirm your coverage.'},
{id:'copies',wk:1,label:'Copies of documents + emergency contacts',exp:'Physical and cloud copies of passport, visa, bookings; share your itinerary with family.'},
{id:'hoho',wk:2,label:'Madinah ziyarah bus booked (optional)',exp:'The City Sightseeing hop-on hop-off covers Quba, Qiblatayn, Uhud, the Trench and Baqi’ on one 24-hour ticket — see the Places tab to book.'},
{id:'money',wk:1,label:'Saudi Riyals + travel card ready',exp:'Cards are widely accepted, but keep cash for taxis, barbers and small shops.'}
]},
{id:'pack',ico:'🧳',title:'Packing',items:[
{id:'ihram',wk:2,bag:'ihram',label:'2 sets of ihram (men)',exp:'A spare set is a mercy after tawaf in the heat. Unstitched white cloth: izar & rida.'},
{id:'belt',wk:2,bag:'ihram',label:'Ihram belt / money pouch',exp:'Keeps documents and cash secure — ihram has no pockets.'},
{id:'abaya',wk:2,bag:'case',label:'Loose, modest clothing (women)',exp:'Women wear normal modest dress in ihram — no face veil or gloves while in ihram.'},
{id:'sandals',wk:3,bag:'ihram',label:'Comfortable sandals + shoe bag',exp:'Men’s ihram footwear should leave the ankle exposed. Shoes get lost at mosque entrances.'},
{id:'unscented',wk:2,bag:'ihram',label:'Unscented soap, sunscreen & lip balm',exp:'Perfumed products are prohibited in ihram — buy unscented before you travel.'},
{id:'meds',wk:2,bag:'carry',label:'Medications + prescriptions',exp:'Carry prescriptions; include painkillers, rehydration salts, blister plasters.'},
{id:'vaseline',wk:1,bag:'ihram',label:'Petroleum jelly / anti-chafing balm',exp:'Unscented — long tawaf and sa’i walks in ihram cause chafing.'},
{id:'adapter',wk:1,bag:'carry',label:'Power adapter (Type G) + power bank',exp:'Saudi uses UK-style 3-pin plugs. A power bank saves you in the Haram.'},
{id:'bottle',wk:1,bag:'carry',label:'Collapsible water bottle / Zamzam cup',exp:'Zamzam dispensers are everywhere in the Haram — stay hydrated.'},
{id:'umbrella',wk:1,bag:'case',label:'Umbrella for sun protection',exp:'Midday courtyard marble is brutal — a light umbrella helps outside the mosque.'},
{id:'dualist',wk:1,bag:'carry',label:'Written personal dua list',exp:'In front of the Kaaba the mind goes blank — write your duas down beforehand.'}
]},
{id:'health',ico:'🩺',title:'Health',items:[
{id:'menacwy',wk:4,label:'Meningitis ACWY vaccination certificate',exp:'Required for Umrah visas — usually at least 10 days before arrival.'},
{id:'jabs',wk:6,label:'Routine vaccines / flu shot up to date',exp:'Millions of pilgrims from around the world — protect yourself and others.'},
{id:'walk',wk:8,label:'Walking practice (8–10k steps/day)',exp:'Tawaf + sa’i is 5+ km; you may walk 15–20 km a day. Train before you go.'},
{id:'doctor',wk:6,label:'Doctor check-up if needed',exp:'Especially for chronic conditions — carry a doctor’s letter for devices/medication.'},
{id:'hygiene',wk:1,label:'Hand sanitiser & masks packed',exp:'The "Umrah flu" is real — prevention keeps your worship strong.'}
]},
{id:'knowledge',ico:'🧠',title:'Knowledge & spirit',items:[
{id:'niyyah',wk:10,label:'Set my intention & spiritual goals for this Umrah',exp:'Write it at the top of the Plan tab — the journey begins in the heart, not at the airport.'},
{id:'learn',wk:4,label:'Learned the Umrah rites step by step',exp:'Review the Umrah tab of this app until each step feels familiar.'},
{id:'talbiyah',wk:3,label:'Memorised the talbiyah',exp:'Labbayk Allahumma labbayk — see the Duas section in More.'},
{id:'tawbah',wk:1,label:'Sincere tawbah (repentance) made',exp:'Arrive with a clean heart — resolve to leave sins behind.'},
{id:'debts',wk:2,label:'Debts settled / disputes resolved',exp:'Seek forgiveness from people you’ve wronged before travelling.'},
{id:'will',wk:2,label:'Wasiyyah (will) written or updated',exp:'A sunnah of preparedness for any traveller.'},
{id:'halal',wk:8,label:'Trip funded from halal earnings',exp:'A pilgrimage funded by the pure is more likely to be accepted.'},
{id:'family',wk:2,label:'Taught travel companions the rites',exp:'Especially children and first-timers — review the steps together.'},
{id:'quiz80',wk:1,label:'Completed the full knowledge circuit (all quiz levels 80%+)',exp:'Work through all six quiz levels below until every one is passed.'}
]}];

var KNOW=[
{t:'📍 The 5 miqats — where ihram begins',b:'<p>You must enter ihram <strong>before</strong> crossing the miqat for your route:</p><ul><li><strong>Dhul-Hulayfah (Abyar Ali)</strong> — coming from Madinah (~450 km from Makkah)</li><li><strong>Al-Juhfah (near Rabigh)</strong> — from Egypt, Syria & the north-west</li><li><strong>Qarn al-Manazil (As-Sayl)</strong> — from Najd, Taif, UAE & most eastern flights</li><li><strong>Yalamlam</strong> — from Yemen & the south</li><li><strong>Dhat Irq</strong> — from Iraq & the north-east</li></ul><p><strong>Flying?</strong> Change into ihram garments before boarding or at a stopover; make your intention when the pilot announces the miqat approach (~30–45 min before Jeddah). Many pilgrims wear ihram from the departure airport to be safe.</p>'},
{t:'🚫 Ihram — what is not allowed',b:'<p>Once in ihram, avoid until your Umrah is complete:</p><ul><li>Cutting hair or nails</li><li>Perfume or scented products (body or garments)</li><li>Men: stitched fitted clothing, covering the head</li><li>Women: face veil (niqab) and gloves — ordinary modest dress otherwise</li><li>Hunting; cutting plants of the Haram</li><li>Marriage contracts or proposals</li><li>Intimacy and anything leading to it</li><li>Arguing, foul language & sin (Quran 2:197)</li></ul><p>Unintentional mistakes are excused. Showering (unscented), changing ihram garments, belts, glasses, watches, umbrellas — all fine.</p>'},
{t:'👕 How to wear the ihram (men) — step by step',b:'<ol style="padding-left:18px"><li><strong>Izar (lower cloth):</strong> hold it behind you at waist height, wrap the left side across the front, then the right side over it; fold the top edge down over itself 2–3 times to lock it. Wear a belt or money pouch over the fold — a belt is fine in ihram.</li><li><strong>Rida (upper cloth):</strong> drape it over both shoulders like a shawl, covering the back and chest; ends hang in front. For the arrival tawaf only, pass it under the right arm (idtiba’) — then cover both shoulders again before praying.</li><li><strong>Footwear:</strong> sandals or slides; the ankles should be uncovered.</li><li><strong>Practise at home</strong> until you can walk, sit and use the bathroom confidently — the number one first-timer anxiety. Safety pins on the izar are used by many pilgrims; scholars differ, so a belt is the cleanest option.</li><li><strong>Sisters:</strong> your normal modest clothing of any colour is your ihram — no face veil or gloves while in ihram.</li></ol>'},
{t:'📱 Nusuk & permits',b:'<p><strong>Nusuk</strong> is the official Saudi pilgrim platform (app + website). You need it for:</p><ul><li><strong>Rawdah visit permit</strong> (Masjid an-Nabawi) — free but limited; book as soon as your dates are fixed</li><li>Umrah eVisa applications & official bookings</li></ul><p>Tawaf and general prayer in both Harams need <strong>no permit</strong> for Umrah pilgrims. Set Nusuk up with your passport details before you travel.</p>'},
{t:'🚄 Getting around',b:'<ul><li><strong>Haramain High-Speed Rail</strong> — Jeddah Airport ↔ Makkah in ~50 min; Makkah ↔ Madinah in ~2.5 hrs. Book online in advance.</li><li><strong>Taxis / Uber / Careem</strong> — plentiful; agree street-taxi fares before riding.</li><li><strong>Buses</strong> — SAPTCO and shuttles connect the cities cheaply.</li><li>Hotels beyond walking distance run free Haram shuttles — ask reception.</li><li><strong>Madinah ziyarah:</strong> the City Sightseeing hop-on hop-off bus (2 routes, 12 stops, 24-hour ticket) reaches Quba, Qiblatayn, Uhud and the Trench with commentary — book it from the Places tab.</li></ul>'},
{t:'💳 Money, SIM & apps',b:'<ul><li>Currency: <strong>Saudi Riyal (SAR)</strong>. Cards & Apple Pay widely accepted; carry some cash.</li><li><strong>eSIM or local SIM</strong> (STC, Mobily, Zain) at the airport — data is cheap and essential.</li><li>Must-have apps: <strong>Nusuk</strong>, <strong>Haramain Rail</strong>, <strong>Careem/Uber</strong>, a prayer-times app — and this one 😉</li><li>Keep small notes for sadaqah, barbers (10–20 SAR) and water.</li></ul>'},
{t:'🌸 Notes for sisters',b:'<ul><li>Ihram is your normal modest clothing — any colour; no niqab or gloves while in ihram.</li><li>No raml (jogging) in tawaf or between the green lights in sa’i — walk normally.</li><li>To exit ihram, trim about a fingertip’s length from the ends of your hair.</li><li>If menstruation begins, all worship continues except salah, tawaf & fasting — delay tawaf until pure; consult a scholar if departure is imminent.</li><li>Pray in the designated women’s sections; agree a family meeting point — signal drops in the Haram.</li></ul>'},
{t:'⏰ Crowd & timing tips',b:'<ul><li>Easiest tawaf: <strong>late night to pre-Fajr</strong>. Hardest: after Isha and around Jumu’ah.</li><li>Arrive 45–60 min before prayer for a spot inside — gates close when full.</li><li>Upper floors take longer per round but are far calmer.</li><li>Never push at the Black Stone — pointing from afar gives the same reward.</li><li>Set a family meeting point (e.g. a numbered gate).</li><li>Drink Zamzam constantly and pace yourself — it’s a marathon of worship, not a sprint.</li></ul>'},
{t:'⚠️ Common mistakes to avoid',b:'<ul><li>Believing each tawaf round has a fixed dua — none are prescribed; only "Rabbana atina…" between the Yamani corner and Black Stone is sunnah.</li><li>Kissing the Yamani corner — it is touched, not kissed; the Black Stone is kissed only if easily reached.</li><li>Raml in all 7 rounds — men do it in the first 3 only, in the arrival tawaf.</li><li>Praying with the right shoulder uncovered after tawaf — cover both shoulders for salah.</li><li>Cutting only a few strands for taqsir — trim from all around the head; halq carries greater reward for men.</li><li>Removing ihram before halq/taqsir is done — restrictions end only after cutting.</li><li>Loud group dhikr in tawaf — it disturbs others; recite individually.</li><li>Selfies and filming in the mataf — guard your khushu and others’ privacy.</li></ul>'}];

var HISTORY=[
{t:'🕋 The Kaaba — the first House',b:'<p>"Indeed, the first House established for mankind was that at Bakkah — blessed and a guidance for the worlds." (Quran 3:96). The Kaaba is the qibla of every prayer you have ever prayed. Ibrahim (AS) and his son Isma’il (AS) raised its foundations, praying: <strong>"Our Lord, accept this from us"</strong> (Quran 2:127). When you stand in the mataf you stand where prophets, companions and centuries of believers have stood before you.</p>'},
{t:'🌊 Hajar, Zamzam & the origin of Sa’i',b:'<p>When Ibrahim (AS) left Hajar and baby Isma’il in the barren valley by Allah’s command, Hajar asked: "Has Allah commanded you to do this?" He said yes. She replied: <strong>"Then He will not abandon us."</strong> She ran seven times between Safa and Marwah searching for water — and Allah caused Zamzam to spring at her baby’s feet (Bukhari 3364). Your sa’i re-enacts her tawakkul, step for step, and Zamzam still flows for you today.</p>'},
{t:'⚖️ The Black Stone & the young Muhammad ﷺ',b:'<p>The Prophet ﷺ said the Black Stone <strong>descended from Paradise whiter than milk, and the sins of the children of Adam blackened it</strong> (Tirmidhi 877). Years before prophethood, when Quraysh rebuilt the Kaaba, the tribes nearly fought over who would set the Stone in place. The young Muhammad ﷺ — already called al-Amin, the Trustworthy — laid it on a cloth so every tribe could lift a corner together, and he set it with his own hands.</p>'},
{t:'⛰️ Cave of Hira — where revelation began',b:'<p>On Jabal an-Nour above Makkah, in the cave of Hira, Jibril (AS) came to the Prophet ﷺ with the first words of the Quran: <strong>"Iqra — Read, in the name of your Lord who created"</strong> (Quran 96:1, Bukhari 3). Everything — every mushaf, every masjid, every Muslim — traces back to that night in that cave you can see from the Haram.</p>'},
{t:'🧭 The qibla change & Masjid al-Qiblatayn',b:'<p>For about 17 months in Madinah the Muslims prayed towards Jerusalem, while the Prophet ﷺ longed for the Kaaba. Then mid-prayer the revelation came: <strong>"Turn your face toward al-Masjid al-Haram"</strong> (Quran 2:144) — and the congregation turned as one. Masjid al-Qiblatayn ("the mosque of the two qiblas") in Madinah marks that moment.</p>'},
{t:'🚪 The Hijrah & the Conquest of Makkah',b:'<p>Persecuted by Quraysh, the Prophet ﷺ left his beloved city, hiding three nights in the cave of Thawr with Abu Bakr (RA): <strong>"Do not grieve; indeed Allah is with us"</strong> (Quran 9:40). Eight years later he returned with ten thousand companions and conquered Makkah <strong>without bloodshed</strong>, forgave his persecutors, and cleansed the Kaaba of its 360 idols while reciting: "Truth has come and falsehood has vanished" (Quran 17:81).</p>'},
{t:'🐘 The Year of the Elephant',b:'<p>The year the Prophet ﷺ was born (~570 CE), Abrahah marched an army with a war elephant to demolish the Kaaba. Allah sent flocks of birds with stones of baked clay and made the army "like eaten straw" — the whole of <strong>Surah al-Fil (105)</strong> tells it. The House has a Protector; armies could not touch what He guards, and you are walking towards it as His invited guest.</p>'},
{t:'🧱 The Kaaba through the ages',b:'<p>The Kaaba has been rebuilt several times — by Quraysh in the Prophet’s ﷺ youth (when funds ran short, they left out part of the original foundation, which is why the <strong>Hijr Isma’il</strong> semicircle stands outside the walls today). The Prophet ﷺ told Aishah: <strong>"Do you not know that when your people rebuilt the Kaaba, they decreased it from the original foundations of Ibrahim?"</strong> (Bukhari 1583). The black kiswah covering is renewed every year, embroidered with gold calligraphy — a tradition of honouring the House that is centuries old.</p>'},
{t:'🗣️ The talbiyah — what you are really saying',b:'<p><strong>Labbayk Allahumma labbayk</strong> — "Here I am, O Allah, here I am." You are answering a call announced by Ibrahim (AS) thousands of years ago: "And proclaim to the people the Hajj; they will come to you on foot and on every lean camel from every distant pass." (Quran 22:27). Every phrase strips away shirk: <em>la sharika lak</em> — You have no partner; all praise, all favour, all sovereignty are Yours alone. Say it with meaning, not momentum — men aloud, women softly, until the tawaf begins.</p>'},
{t:'📍 Landmarks and what they mean',b:'<ul><li><strong>Maqam Ibrahim</strong> — the stone Ibrahim (AS) stood on while raising the Kaaba’s walls; his footprints were preserved in it (Quran 2:125).</li><li><strong>Hijr Isma’il</strong> — the semicircle was part of the original Kaaba; praying inside it counts as praying inside the Kaaba (Tirmidhi 876).</li><li><strong>Multazam</strong> — the wall between the Black Stone and the door, where dua is beloved.</li><li><strong>The Yamani corner</strong> — touched (not kissed) each round when possible.</li></ul>'}];

var VIRTUES=[
{t:'🧼 Umrah wipes away sins',b:'<p>The Prophet ﷺ said: <strong>"Umrah to Umrah is an expiation for the sins committed between them, and the accepted Hajj has no reward except Paradise."</strong> (Bukhari 1773). Whoever performs the pilgrimage without obscenity or wickedness "returns as the day his mother bore him" (Muslim 1350). You come home with a clean slate — guard it.</p>'},
{t:'💰 It removes poverty',b:'<p><strong>"Follow up between Hajj and Umrah, for they remove poverty and sins just as the bellows removes the dross of iron, gold and silver."</strong> (Tirmidhi 810). The money you spend on this journey is never a loss.</p>'},
{t:'🤝 You are the guest of Allah',b:'<p><strong>"The pilgrims of Hajj and Umrah are the delegation of Allah: if they call upon Him, He answers them, and if they ask His forgiveness, He forgives them."</strong> (Ibn Majah 2892). Arrive with your dua list ready — you have an audience with the Most Generous Host.</p>'},
{t:'🛡️ The jihad of the weak',b:'<p>The Prophet ﷺ said: <strong>"The jihad of the elderly, the young, the weak and women is Hajj and Umrah."</strong> (Nasai 2626). And when Aishah (RA) asked if women have jihad, he said: "Jihad in which there is no fighting — Hajj and Umrah." (Ibn Majah 2901). Every drop of sweat in the mataf is counted.</p>'},
{t:'🕋 The reward of tawaf',b:'<p><strong>"Whoever performs tawaf around this House seven times and keeps count of it is like one who frees a slave."</strong> With every step "a sin is erased and a good deed is recorded" (Tirmidhi 959). And tawaf is worship you can ONLY do here — fill your trip with it.</p>'},
{t:'🕌 100,000 prayers — the mathematics of the Haram',b:'<p><strong>"One prayer in this masjid of mine is better than a thousand prayers elsewhere, except al-Masjid al-Haram — and one prayer in al-Masjid al-Haram is better than a hundred thousand prayers elsewhere."</strong> (Ibn Majah 1406). One Fajr in the Haram outweighs ~55 years of prayers. Five daily prayers for a week here is a lifetime of reward — never sleep through a congregation.</p>'},
{t:'💧 Zamzam — blessed water',b:'<p>The Prophet ﷺ said: <strong>"Zamzam water is for whatever it is drunk for."</strong> (Ibn Majah 3062) and called it "blessed — a food that nourishes and a cure for illness" (Muslim 2473). Drink your fill, face the qibla, and ask Allah for exactly what you need — knowledge, cure, forgiveness.</p>'},
{t:'🕋 The Prophet’s ﷺ own four Umrahs',b:'<p>Anas (RA) was asked how many Umrahs the Prophet ﷺ performed: <strong>"Four — the Umrah of Hudaybiyyah, the Umrah of the following year (al-Qada), the Umrah from al-Ji’ranah, and the Umrah with his Hajj."</strong> (Bukhari 1778). He also ordered Aishah’s brother to take her to <strong>Tan’eem</strong> so she could perform an extra Umrah (Bukhari 1784) — the very miqat you can use for a second Umrah today.</p>'},
{t:'❤️ Makkah — the most beloved land',b:'<p>Leaving for the Hijrah, the Prophet ﷺ said of Makkah: <strong>"By Allah, you are the best of Allah’s land, and the most beloved of Allah’s land to Allah. Had I not been driven out of you, I would never have left."</strong> (Tirmidhi 3925). The Haram is a sanctuary where even the trees and game are protected — carry its adab everywhere.</p>'}];

var MADINAH=[
{t:'🕌 1,000 prayers — Masjid an-Nabawi',b:'<p><strong>"One prayer in this masjid of mine is better than a thousand prayers anywhere else, except al-Masjid al-Haram."</strong> (Bukhari 1190). The Prophet ﷺ built this mosque with his own hands. Aim to pray all 40 prayers there if your stay allows — but know the famous "40 prayers" hadith is graded weak; the 1,000× virtue applies to every single prayer regardless.</p>'},
{t:'🌹 The Rawdah — a garden of Paradise',b:'<p><strong>"Between my house and my minbar is a garden (rawdah) from the gardens of Paradise."</strong> (Bukhari 1195). It is the small area marked today by green carpets. Entry requires a free timed permit on Nusuk — book it the day your travel dates are fixed, and pray there with presence, not photos.</p>'},
{t:'🤲 Greeting the Prophet ﷺ',b:'<p>Stand before the blessed grave calmly and say: <strong>"As-salamu ’alayka ya Rasulallah"</strong> — then greet Abu Bakr (RA) and ’Umar (RA) who rest beside him. No shouting, no pushing, no backs turned in dua towards other worshippers. He ﷺ said: "There is no one who sends salam upon me but Allah returns my soul to me so that I may return his salam." (Abu Dawud 2041).</p>'},
{t:'🛡️ A protected sanctuary',b:'<p>Madinah, like Makkah, is a haram — a sacred sanctuary (Muslim 1374). The Prophet ﷺ said: <strong>"There are angels at the entrances of Madinah: neither plague nor the Dajjal can enter it."</strong> (Bukhari 1880). And: "Madinah expels its impurities as the furnace expels the dross of iron." (Bukhari 1871).</p>'},
{t:'🍃 The virtue of living & dying there',b:'<p><strong>"Whoever is able to die in Madinah, let him die there, for I will intercede for the one who dies there."</strong> (Tirmidhi 3917). And: "None patiently endures the hardship of Madinah except that I will be an intercessor or witness for him on the Day of Resurrection." (Muslim 1374).</p>'},
{t:'🕌 Masjid Quba — an Umrah every visit',b:'<p>The first mosque of Islam, founded on taqwa (Quran 9:108). <strong>"Whoever purifies himself in his house, then comes to Masjid Quba and prays in it, has the reward of an Umrah."</strong> (Ibn Majah 1412). The Prophet ﷺ visited every Saturday — make wudu at your hotel and go at least once.</p>'},
{t:'⛰️ Uhud & the martyrs',b:'<p><strong>"Uhud is a mountain that loves us and we love it."</strong> (Bukhari 4083). At its foot rest Hamza (RA), the Prophet’s ﷺ uncle and the Master of Martyrs, with seventy companions of the Battle of Uhud. Visit after Fajr, give salam, and reflect on what they gave for the deen that reached you.</p>'},
{t:'🌴 Ajwa dates & the blessing of Madinah',b:'<p>The Prophet ﷺ said: <strong>"Whoever eats seven Ajwa dates in the morning will not be harmed that day by poison or magic."</strong> (Bukhari 5779). He also made dua: "O Allah, bless Madinah with twice the blessings You gave Makkah." (Bukhari 1885). Bring Ajwa home as your gift.</p>'},
{t:'🧳 Practical: Madinah is not a rite of Umrah',b:'<p>Visiting Madinah is a beloved, highly virtuous journey — one of only three mosques worth travelling to (Bukhari 1189) — but it is <strong>not part of the Umrah rites</strong> and there is no ihram for it. Plan 2–4 relaxed days: prayers in the Haram, Rawdah permit, Quba, Qiblatayn, Uhud and Baqi. The pace is calmer than Makkah — use it for reflection and long duas.</p>'}];

var FIQHQA=[
{t:'❓ Can I perform Umrah on behalf of someone else?',b:'<p>Yes — <strong>badal Umrah</strong> for a deceased person, or one permanently unable (chronic illness, old age), is established: the Prophet ﷺ heard a man saying "Labbayk on behalf of Shubrumah" and allowed it once the man had first performed his own (Abu Dawud 1811). So: your own Umrah first, then on behalf of others — one person per Umrah.</p>'},
{t:'❓ Can I do more than one Umrah in a single trip?',b:'<p>Yes. The Prophet ﷺ ordered ’Abdur-Rahman to take his sister Aishah (RA) to <strong>Tan’eem (Masjid Aisha)</strong> to perform an Umrah from there (Bukhari 1784). Exit the Haram boundary, assume a fresh ihram, and repeat the rites. Scholars differ on how much repetition is ideal — quality and khushu come before quantity.</p>'},
{t:'❓ What if my wudu breaks during tawaf?',b:'<p>Renew your wudu and return. The majority hold you resume from where you stopped in the current round or repeat that round to be safe; a completed round is not lost. Crowding makes this common — no panic, it does not ruin your Umrah.</p>'},
{t:'❓ Can I rest during tawaf or sa’i?',b:'<p>Yes — you may pause to rest, drink Zamzam, or pray an obligatory prayer when the iqamah is called, then continue from where you left off. The rites are acts of devotion, not endurance tests: "Allah intends for you ease" (Quran 2:185).</p>'},
{t:'❓ What does a menstruating woman do?',b:'<p>She assumes ihram at the miqat like everyone (ihram does not require purity), recites talbiyah and dhikr, and <strong>delays tawaf — and the sa’i after it — until she is pure</strong> (Bukhari 305, the Prophet’s ﷺ instruction to Aishah). Everything else — dua, dhikr, listening to Quran — continues. If departure is imminent, ask a scholar about the concessions.</p>'},
{t:'❓ Are raml and idtiba’ obligatory?',b:'<p>No — both are sunnah for men in the arrival tawaf only. Skipping them (crowds, weakness, forgetting) affects nothing. The obligations of tawaf are: purity, covering the awrah, seven complete rounds around the House, keeping the Kaaba on your left.</p>'},
{t:'❓ Is tawaf valid on the upper floors or in a wheelchair?',b:'<p>Fully valid. The upper floors and the mataf ring circle the same House, and the Prophet ﷺ himself performed tawaf mounted on a camel (Bukhari 1607). Free wheelchair services and paid pushers are available — ask the Haram staff near the gates.</p>'},
{t:'❓ Does talking during tawaf break it?',b:'<p>No — "Tawaf around the House is like salah, except that Allah has permitted speech in it; so whoever speaks, let him say only good." (Tirmidhi 960). Necessary talk is fine; idle chatter and phone-scrolling waste a moment you may never get back.</p>'},
{t:'❓ Do I shorten my prayers as a traveller?',b:'<p>A traveller may shorten 4-rakah prayers to 2 (qasr) — but when praying <strong>behind the Haram imam you complete the full prayer</strong> with the congregation. Most pilgrims simply pray everything in congregation at the Haram, which is the whole point of being there.</p>'},
{t:'❓ Must ihram garments be new and white?',b:'<p>No — clean and unstitched is the requirement for men; white is recommended, new is not required. Washing your ihram or changing into a spare set while in ihram is perfectly fine. For women, any modest clothing in any colour is their ihram.</p>'}];

var SCAMS=[
{t:'🛡️ Rule #1 — permits are free, donations go through official channels',b:'<p>Every permit a pilgrim needs (Rawdah visit, Umrah permit in season) is <strong>free on the Nusuk app</strong>. Anyone selling you a "permit", "slot" or "VIP access" is selling you nothing. And in Saudi Arabia, collecting donations in streets and mosques is <strong>illegal outside official platforms</strong> — the Kingdom’s official donation platform is <strong>Ehsan (ehsan.sa)</strong>. When in doubt: if it isn’t Nusuk or Ehsan, walk away politely.</p>'},
{t:'🎭 Street begging with heartbreaking stories',b:'<p>Around the Haramain you will meet rehearsed stories: a mother with a sleeping baby (sometimes rented for the day), "my wallet was stolen and I need a ticket home", "my child needs surgery", a shown photo of a sick relative. Organised gangs run many of these, and they target pilgrims whose hearts are soft after worship. <strong>Your mercy is not naive — but your money should be smart:</strong> give through Ehsan, your trusted charity at home, or to people whose situation you actually know. Begging is illegal in the Haramain; report persistent cases to security rather than engaging.</p>'},
{t:'📦 Fake Umrah packages & visa fraud',b:'<p>The classic: a too-cheap package on social media, payment by bank transfer only, then the "agent" vanishes — or you land with no hotel booking. <strong>Protect yourself:</strong> book through <strong>umrah.nusuk.sa</strong> (every provider there is licensed by the Ministry of Hajj & Umrah) or an agent whose ministry accreditation you can verify; in the UK/EU check ATOL/ABTA protection; pay by credit card, never untraceable transfer; and treat any "guaranteed visa in 24 hours" claim as a red flag.</p>'},
{t:'🕌 The badal-Umrah money trap',b:'<p>Online services take payment to perform Umrah "on behalf of your deceased parents" — and many simply pocket the money; you have no way to verify anything happened. If you want badal for a loved one, arrange it through <strong>someone you personally know and trust</strong>, or do it yourself from Tan’eem while you’re there (see the fiqh Q&A). Reward cannot be bought from a webshop.</p>'},
{t:'🎣 Phishing: fake Nusuk sites, apps & OTP theft',b:'<p>Scammers clone the Nusuk website and app to harvest passport details, card numbers and OTP codes. <strong>Only use nusuk.sa / umrah.nusuk.sa</strong> typed directly, or the app from the official Apple/Google stores. Never share an OTP with anyone — no real official will ever ask. Never hand your passport to a "helper" you just met.</p>'},
{t:'💺 "VIP access" touts',b:'<p>Men near the mataf offering — for a fee — to "get you to the Black Stone", into the Rawdah, or a "private tawaf". The Rawdah is a free Nusuk permit; the Black Stone is reached by patience or pointed to from afar with full reward; there is no private tawaf. Paying touts funds harassment of pilgrims and usually buys nothing.</p>'},
{t:'♿ Wheelchair, taxi & money rip-offs',b:'<p>Unofficial wheelchair pushers may quote one price and demand triple at the end — use the <strong>official wheelchair desks</strong> inside the Haram or agree a written price first. Street taxis: agree the fare before the door closes, or use Careem/Uber. Money changers: count your riyals at the counter. And the "found gold ring — buy it from me cheap" trick is brass, not gold.</p>'},
{t:'📱 "You won a free Umrah!" messages',b:'<p>WhatsApp and Facebook messages announcing you won a free Umrah, an iPhone-and-Umrah bundle, or a charity lottery — just pay a small "processing fee" or share your details. No ministry runs lotteries by WhatsApp. Delete, block, and warn the family group.</p>'},
{t:'💳 QR codes & card machines collecting "sadaqah"',b:'<p>People with card readers or printed QR codes collecting for "mosque construction", "orphans" or "Quran printing" in streets and hotel lobbies. Unregulated collection is illegal in Saudi Arabia precisely because of fraud. Scan nothing. Your sadaqah does more through <strong>Ehsan (ehsan.sa)</strong>, your home mosque, or a charity whose registration you can check.</p>'},
{t:'✅ If it happens: report it',b:'<p>Don’t argue with scammers — walk away and report: any Haram security officer, the police at <strong>911</strong>, or the Ministry of Hajj & Umrah care line <strong>1966</strong>. Reporting protects the pilgrims who come after you. And if you were fooled — your intention was charity, and "actions are but by intentions" (Bukhari 1): your reward is with Allah; get wiser, not colder.</p>'}];

var KIDSQ=[
{q:'What is the name of the black cube we walk around? 🕋',o:['The Kaaba','A castle','A big tent'],a:0,e:'The Kaaba — the House of Allah that Prophet Ibrahim built with his son Isma’il!'},
{q:'How many times do we walk around the Kaaba? 🔄',o:['3 times','7 times','100 times'],a:1,e:'Seven times — and it’s called tawaf. Try counting to 7 on your fingers!'},
{q:'What special water do we drink in Makkah? 💧',o:['Zamzam','Lemonade','Rainwater'],a:0,e:'Zamzam! Allah made it spring up for baby Isma’il thousands of years ago — and it still flows today.'},
{q:'We walk 7 times between two small hills. What are they called? ⛰️',o:['Safa & Marwah','Uhud & Thawr','Mina & Arafat'],a:0,e:'Safa and Marwah — just like Isma’il’s mother Hajar, who ran between them looking for water.'},
{q:'What do pilgrims keep saying on the way to Makkah? 🗣️',o:['Labbayk Allahumma labbayk!','Happy birthday!','Let’s go, let’s go!'],a:0,e:'"Labbayk Allahumma labbayk" — Here I am, O Allah, here I am!'},
{q:'What do the men wear for Umrah? 👕',o:['Two white cloths','A superhero cape','A black suit'],a:0,e:'Two simple white cloths called ihram — rich or poor, everyone dresses the same, because we are all equal before Allah.'},
{q:'Which city has the Prophet’s ﷺ beautiful mosque with the green dome? 🕌',o:['Madinah','Jeddah','Riyadh'],a:0,e:'Madinah! Praying there once is better than a thousand prayers anywhere else.'},
{q:'What happens at the very end of Umrah? ✂️',o:['A haircut!','A big cake','Fireworks'],a:0,e:'Boys shave or cut their hair, girls trim a tiny bit — and the Umrah is complete. Mabrook! 🎉'}];

var RITES=[
{id:'ph1',ico:'🤍',title:'Phase 1 · Ihram at the miqat',hn:'"Actions are but by intentions, and every person shall have what they intended." — Bukhari 1',steps:[
{id:'ghusl',why:'The Prophet ﷺ bathed before entering ihram (Tirmidhi 830) — you meet Allah’s House purified inside and out.',b:'Ghusl & grooming',p:'Shower, trim nails, remove unwanted hair. Men may apply perfume to the body (not the garments) before intention.'},
{id:'garb',why:'Unstitched cloth strips away rank and wealth: king and labourer stand identical before Allah, dressed as they will be shrouded.',b:'Wear ihram garments',p:'Men: two unstitched white cloths (izar & rida), sandals. Women: ordinary modest clothing.'},
{id:'salah2',why:'The Prophet ﷺ entered ihram at Dhul-Hulayfah after praying there — beginning the journey with salah is his way.',b:'Pray 2 rakahs (if possible)',p:'Recommended before ihram — an obligatory prayer, or 2 rakahs of wudu.'},
{id:'niyyah',why:'"Actions are but by intentions" (Bukhari 1). The miqats are boundaries the Prophet ﷺ himself appointed (Bukhari 1524).',b:'Make the intention at the miqat',p:'The rules of ihram now apply.',dua:{ar:'لَبَّيْكَ اللَّهُمَّ عُمْرَةً',tl:'Labbayk Allahumma ’Umrah',tr:'Here I am, O Allah, for Umrah.'}},
{id:'talb',why:'The talbiyah is your answer to Ibrahim’s call (Quran 22:27); the Prophet’s ﷺ own words are recorded in Bukhari 1549.',b:'Recite the talbiyah abundantly',p:'Men aloud, women softly — keep reciting until you begin tawaf.',dua:{ar:'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ',tl:'Labbayk Allahumma labbayk, labbayka la sharika laka labbayk, innal-hamda wan-ni’mata laka wal-mulk, la sharika lak',tr:'Here I am O Allah, here I am. You have no partner, here I am. All praise, favour and sovereignty are Yours. You have no partner.'}}
]},
{id:'ph2',ico:'🕋',title:'Phase 2 · Tawaf — 7 rounds',hn:'"Whoever performs tawaf around this House seven times and keeps count of it, it is like freeing a slave." — Tirmidhi 959',steps:[
{id:'wudu',why:'"Tawaf around the House is like salah" (Tirmidhi 960) — so it needs the purity of salah.',b:'Make wudu — required for tawaf',p:'Tawaf is not valid without wudu. Make it before you enter; if it breaks mid-tawaf, renew it and continue. Enter the mosque with the right foot:',dua:{ar:'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',tl:'Allahumma-ftah li abwaba rahmatik',tr:'O Allah, open the gates of Your mercy for me.'}},
{id:'idtiba',why:'The companions bared their right shoulders to show Quraysh their strength; the Prophet ﷺ kept the practice in the arrival tawaf.',b:'Idtiba’ (men): uncover the right shoulder',p:'Pass the rida under the right arm and over the left shoulder — for this tawaf only.'},
{id:'start',why:'’Umar (RA) kissed the Stone saying "I know you are a stone… had I not seen the Prophet ﷺ kiss you I would not" (Bukhari 1597) — pure following, not superstition.',b:'Start at the Black Stone line',p:'Face the Stone, raise your hand and say "Bismillahi wallahu akbar". Kiss or touch it only if easy — never push.'},
{id:'rounds',why:'Seven is the number the Prophet ﷺ performed; keeping count is itself part of the reward (Tirmidhi 959).',b:'Complete 7 rounds — use the counter above',p:'Counter-clockwise, Kaaba on your left. Men walk briskly (raml) in rounds 1–3. Make any dhikr and dua you love.'},
{id:'yamani',why:'He touched the Yamani corner without kissing it and recited this dua between the two corners (Abu Dawud 1892).',b:'Between the Yamani corner & Black Stone',p:'Touch the Yamani corner if easy (don’t kiss it), and recite:',dua:{ar:'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',tl:'Rabbana atina fid-dunya hasanah wa fil-akhirati hasanah wa qina ’adhaban-nar',tr:'Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire. (Quran 2:201)'}},
{id:'maqam',why:'"Take the Maqam of Ibrahim as a place of prayer" (Quran 2:125) — the Prophet ﷺ recited this very verse then prayed there (Muslim 1218).',b:'Pray 2 rakahs behind Maqam Ibrahim',p:'Cover both shoulders first. Al-Kafirun in the first rakah, al-Ikhlas in the second. If crowded, pray anywhere in the mosque.'},
{id:'zamzam',why:'After the two rakahs he ﷺ drank Zamzam before sa’i (Muslim 1218) — you follow his sequence step for step.',b:'Drink Zamzam water',p:'Drink your fill and make dua — "Zamzam water is for whatever it is drunk for." (Ibn Majah 3062)'}
]},
{id:'ph3',ico:'⛰️',title:'Phase 3 · Sa’i — 7 laps',hn:'"Indeed, Safa and Marwah are among the symbols of Allah." — Quran 2:158',steps:[
{id:'safa',why:'"I begin with what Allah began with" (Muslim 1218) — Safa is named first in Quran 2:158.',b:'Ascend Safa, face the Kaaba & make dua',p:'Recite the ayah "Innas-Safa wal-Marwah…", praise Allah facing the Kaaba, and repeat this dhikr with your own duas three times:',dua:{ar:'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ، أَنْجَزَ وَعْدَهُ وَنَصَرَ عَبْدَهُ وَهَزَمَ الْأَحْزَابَ وَحْدَهُ',tl:'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa ’ala kulli shay’in qadir. La ilaha illallahu wahdah, anjaza wa’dah, wa nasara ’abdah, wa hazamal-ahzaba wahdah',tr:'None has the right to be worshipped but Allah alone, without partner. His is the dominion and the praise, and He is able to do all things. He fulfilled His promise, gave victory to His servant, and defeated the confederates alone.'}},
{id:'laps',why:'The jog between the lights marks the dip in the valley where Hajar ran to keep her son in sight.',b:'Walk 7 laps — use the counter above',p:'Safa → Marwah is one lap; you finish on Marwah. Men jog lightly between the green lights. Dhikr and dua freely — no fixed formula.'},
{id:'marwah',why:'He repeated the same praise and dua on each hill (Muslim 1218) — persistence in dua is the lesson of sa’i.',b:'On Marwah each lap: face the Kaaba & repeat',p:'Same praise and dua as on Safa. Sa’i commemorates Hajar’s trust in Allah — walk it with reflection.'}
]},
{id:'ph4',ico:'✂️',title:'Phase 4 · Halq / Taqsir',hn:'"O Allah, forgive those who shave their heads." He said it three times, and the fourth: "…and those who shorten." — Bukhari 1727',steps:[
{id:'cut',why:'Cutting the hair ends ihram; his dua for those who shave shows halq is the higher choice for men (Bukhari 1727).',b:'Men: shave (halq) or trim all around (taqsir)',p:'Shaving carries the greater reward. Licensed barbershops cluster around the Marwah exit.'},
{id:'cutw',why:'Women are commanded to shorten, not shave — the Prophet ﷺ said "women do not shave, they trim" (Abu Dawud 1984).',b:'Women: trim a fingertip’s length',p:'Gather the hair and cut about 2 cm from the ends — never shave.'},
{id:'done',b:'Your Umrah is complete! 🎉',p:'All ihram restrictions are lifted. May Allah accept it — make shukr, and keep filling your days with worship (Daily tab).'}
]}];

var DAILY=[
{id:'salah',ico:'🕌',title:'Salah in the Haram',hn:'"One prayer in al-Masjid al-Haram is better than one hundred thousand prayers elsewhere." — Ibn Majah 1406',items:[
{id:'fajr',label:'Fajr in congregation',ref:'Muslim 656',exp:'Isha in congregation is like praying half the night; Fajr in congregation completes the whole night. (Muslim 656)',pts:15,stk:'fajr'},
{id:'dhuhr',label:'Dhuhr in congregation',pts:12},
{id:'asr',label:'Asr in congregation',pts:12},
{id:'maghrib',label:'Maghrib in congregation',pts:12},
{id:'isha',label:'Isha in congregation',pts:15},
{id:'tahajjud',label:'Tahajjud in the Haram',ref:'Bukhari 1145',exp:'The Haram at 3am is an experience you will never forget.',pts:12,stk:'tahaj'},
{id:'duha',label:'Duha prayer',pts:6},
{id:'madhkar',label:'Morning adhkar',pts:5},
{id:'eadhkar',label:'Evening adhkar',pts:5}
]},
{id:'quran',ico:'📖',title:'Quran',hn:'"Read the Quran, for it will come as an intercessor for its companions on the Day of Resurrection." — Muslim 804',apps:[{i:'📖',n:'Tarteel AI',d:'Recite and get tajweed correction; memorisation tracking',u:'https://tarteel.ai/'},{i:'🕋',n:'Quran.com',d:'Read, listen and study with translations',u:'https://quran.com/'}],items:[
{id:'recite',label:'Recited Quran (facing the Kaaba if you can)',pts:10,stk:'quran'},
{id:'tadabbur',label:'Reflected on the meaning (tadabbur)',pts:8},
{id:'memorize',label:'Memorised new ayah(s)',pts:8},
{id:'listen',label:'Listened to the Haram recitation attentively',pts:5}
]},
{id:'dhikr',ico:'📿',title:'Dhikr & dua',hn:'Fill your day with remembrance in the most sacred place on Earth.',apps:[{i:'🤲',n:'Life with Allah',d:'Morning & evening adhkar and duas from the Sunnah, with audio',u:'https://lifewithallah.com/app'},{i:'🛡️',n:'Hisnul Muslim (Fortress of the Muslim)',d:'The classic dua collection — every occasion, referenced',u:'https://hisnmuslim.com/'},{i:'📿',n:'Tasbih & my dua list',d:'Built in — Daily › Tools',go:['daily','tools']},{i:'🕋',n:'Umrah duas with audio',d:'Built in — More › Duas',go:['more','duas']}],items:[
{id:'istighfar',label:'Istighfar ×100',pts:6},
{id:'salawat',label:'Salawat on the Prophet ﷺ ×100',pts:6},
{id:'dhikr100',label:'La ilaha illallah / SubhanAllah dhikr',pts:5},
{id:'dualist',label:'Went through my personal dua list',exp:'Use it in the mataf, between adhan & iqamah, and in sujood.',pts:8},
{id:'duaothers',label:'Made dua for family & the ummah',ref:'Muslim 2733',exp:'The angel says: "Amin, and for you the same."',pts:5}
]},
{id:'extra',ico:'✨',title:'Extra acts of worship',hn:'"Tawaf around the House is like prayer, except that you may speak in it." — Tirmidhi 960',items:[
{id:'ntawaf',label:'Nafl tawaf (7 rounds)',exp:'The greatest voluntary act available only in Makkah — do as many as you can.',pts:15,stk:'tawaf'},
{id:'zamzam',label:'Drank Zamzam with dua',pts:5},
{id:'sadaqah',label:'Gave sadaqah',pts:8},
{id:'helped',label:'Helped a fellow pilgrim',exp:'Pushed a wheelchair, shared water, gave directions — service is worship.',pts:8},
{id:'ziyarah',label:'Visited a ziyarah place (Places tab)',pts:6},
{id:'patience',label:'Kept patience in the crowds',exp:'No pushing, no arguing — crowd patience is part of the test.',pts:6},
{id:'tongue',label:'Guarded the tongue',pts:5}
]}];

var TOUR={url:'https://city-sightseeing.com/en/125/medina/478/hop-on-hop-off-al-madinah',stops:[
{n:1,r:'green',t:'Al Masjid an Nabawi',id:'nabawi'},{n:2,r:'green',t:'Al-Baqi’',id:'baqi'},{n:3,r:'green',t:'Al Manakha Square',id:'manakha'},{n:4,r:'green',t:'Al Salam Gate',id:'babsalam'},
{n:1,r:'red',t:'Uhud Battlefield',id:'uhud'},{n:2,r:'red',t:'Al-Noor Mall',id:'noormall'},{n:3,r:'red',t:'Sultanah / Abu Bakr as-Siddiq Rd',id:'sultanah'},{n:4,r:'red',t:'Al Qiblatain Mosque',id:'qiblatain'},{n:5,r:'red',t:'The Trench Battlefield',id:'khandaq'},{n:6,r:'red',t:'Masjid Quba',id:'quba'},{n:7,r:'red',t:'Al Hijaz Railway Station',id:'hijazrail'},{n:8,r:'red',t:'Quba Square',id:'qubasq'}]};
var GLABEL={haram:'🕋 The Haram',ziyarah:'🕌 Ziyarah in Makkah',hajj:'⛺ The Hajj sites',museum:'🏛️ Museums & culture',trip:'🚗 Day trips',mharam:'🕌 The Prophet’s Mosque & around',mosques:'🕌 Historic mosques',history:'⛰️ Battlefields, wells & history',tour:'🚌 Hop-on hop-off & practical stops'};
var GORDER={makkah:['haram','ziyarah','hajj','museum','trip'],madinah:['mharam','mosques','history','tour']};
var PLACES=[
/* ── MAKKAH · The Haram ── */
{id:'haram',ll:[21.4225,39.8262],city:'makkah',g:'haram',i:'🕋',n:'Masjid al-Haram & the Kaaba',q:'Masjid al-Haram Makkah',d:'The House of Allah, qibla of the world, site of your tawaf. "The first House established for mankind" (Quran 3:96); every prayer here is worth 100,000 (Ibn Majah 1406).',tip:'Landmarks inside: Hajar al-Aswad, Maqam Ibrahim, Hijr Isma’il, the Multazam & the Yamani corner.'},
{id:'hijr',ll:[21.4225,39.8262],city:'makkah',g:'haram',i:'🌙',n:'Hijr Isma’il & Maqam Ibrahim',q:'Masjid al-Haram Makkah',d:'The semicircle beside the Kaaba was part of Ibrahim’s original building — praying inside it counts as praying inside the Kaaba (Tirmidhi 876). Maqam Ibrahim is the stone he stood on while raising the walls (Quran 2:125).',tip:'Try the Hijr late at night after tawaf; pray your 2 rakahs anywhere behind the Maqam if the area is packed.'},
{id:'zamzam',ll:[21.4225,39.8262],city:'makkah',g:'haram',i:'💧',n:'The Well of Zamzam',q:'Zamzam Well Makkah',d:'Sprang at baby Isma’il’s feet as Hajar searched between the hills (Bukhari 3364). "Zamzam water is for whatever it is drunk for" (Ibn Majah 3062).',tip:'The well itself is now beneath the mataf; chilled and room-temperature dispensers are on every floor. Face the qibla and make dua as you drink.'},
{id:'safa',ll:[21.4234,39.8278],city:'makkah',g:'haram',i:'⛰️',n:'Safa & Marwah (the Mas’a)',q:'Safa and Marwah Makkah',d:'"Indeed Safa and Marwah are among the symbols of Allah" (Quran 2:158). The two hills of Hajar’s seven runs, now an air-conditioned 450 m gallery inside the mosque.',tip:'Wheelchair lanes run down the middle; the green lights mark where men jog. Begin at Safa, finish at Marwah.'},
/* ── MAKKAH · Ziyarah ── */
{id:'hira',ll:[21.4575,39.8595],city:'makkah',g:'ziyarah',i:'⛰️',n:'Jabal an-Nour & the Cave of Hira',q:'Jabal al-Nour Makkah',d:'Where the first revelation "Iqra" descended upon the Prophet ﷺ (Bukhari 3).',tip:'A steep 45–90 min climb — go after Fajr, take water. Viewing from below also suffices; see the Revelation Exhibition at its foot.'},
{id:'thawr',ll:[21.3776,39.8438],city:'makkah',g:'ziyarah',i:'🏔️',n:'Jabal Thawr',q:'Jabal Thawr Makkah',d:'The cave where the Prophet ﷺ and Abu Bakr hid for three nights during the Hijrah — "Do not grieve; indeed Allah is with us" (Quran 9:40).',tip:'A tougher climb than Hira; most pilgrims view it from the road on a ziyarah tour.'},
{id:'birth',ll:[21.423,39.83],city:'makkah',g:'ziyarah',i:'🏠',n:'Birthplace of the Prophet ﷺ (Makkah Library)',q:'Makkah Al Mukarramah Library',d:'By long-standing tradition the site of the house of Aminah where the Prophet ﷺ was born in the Year of the Elephant, in the Shi’b Ali quarter. Today it houses a library.',tip:'A few minutes’ walk from the Safa side of the Haram. Viewed from outside — it is not a place of worship; reflect, don’t ritualise.'},
{id:'abuqubays',ll:[21.4225,39.83],city:'makkah',g:'ziyarah',i:'🏔️',n:'Jabal Abu Qubays',q:'Jabal Abu Qubais Makkah',d:'The mountain rising directly east of the Haram, held by tradition to be the first mountain placed on earth and the place the Black Stone was safeguarded during the flood.',tip:'Now crowned by a royal palace; visible from the Safa end of the mataf — no visit needed.'},
{id:'rayah',city:'makkah',g:'ziyarah',i:'🚩',n:'Masjid ar-Rayah',q:'Masjid Al Rayah Makkah',d:'"The Mosque of the Banner" — by tradition the spot where the Prophet ﷺ planted his standard as he entered Makkah at the Conquest of 8 AH, forgiving the city that had expelled him.',tip:'In the Jarwal district, ~15 min walk north-west of the Haram.'},
{id:'taneem',ll:[21.4693,39.8016],city:'makkah',g:'ziyarah',i:'🕌',n:'Masjid Aisha (Tan’eem)',q:'Masjid Aisha Taneem Makkah',d:'The nearest boundary of the Haram — where the Prophet ﷺ sent Aishah (RA) to take ihram for her Umrah (Bukhari 1784). Take ihram here for an additional Umrah.',tip:'10–15 min taxi; free buses often run. Showers and ihram shops on site.'},
{id:'jiranah',ll:[21.567,39.956],city:'makkah',g:'ziyarah',i:'🕌',n:'Masjid al-Ji’ranah',q:'Masjid Al Jiranah Makkah',d:'Where the Prophet ﷺ assumed ihram for his Umrah after the Battle of Hunayn (Bukhari 1778) — one of his four Umrahs. A miqat for those already in Makkah.',tip:'~25 km north-east; far calmer than Tan’eem for a second Umrah.'},
{id:'hudaybiyyah',ll:[21.438,39.696],city:'makkah',g:'ziyarah',i:'🌳',n:'Masjid al-Hudaybiyyah',q:'Masjid Al Hudaibiyah Makkah',d:'Site of the Treaty of Hudaybiyyah (6 AH) and the Pledge under the Tree — "Allah was pleased with the believers when they pledged allegiance to you under the tree" (Quran 48:18). Also a miqat on the western Haram boundary.',tip:'~25 km west on the Jeddah road; the old mosque ruins stand beside the modern one.'},
{id:'mualla',ll:[21.43,39.8283],city:'makkah',g:'ziyarah',i:'🌿',n:'Jannat al-Mu’alla',q:'Jannat al-Mualla Makkah',d:'Makkah’s ancient cemetery — resting place of Khadijah (RA), the Prophet’s ﷺ beloved first wife, and of his grandfather Abdul-Muttalib and uncle Abu Talib.',tip:'Give salam to the deceased; visiting hours are limited and entry is for men.'},
{id:'jinn',ll:[21.431,39.8288],city:'makkah',g:'ziyarah',i:'🕌',n:'Masjid al-Jinn',q:'Masjid al-Jinn Makkah',d:'Where a group of jinn listened to the Prophet ﷺ reciting Quran and embraced Islam — the event behind Surah al-Jinn (72).',tip:'A short walk north of the Haram, near Jannat al-Mu’alla.'},
/* ── MAKKAH · Hajj sites ── */
{id:'arafat',ll:[21.3549,39.9841],city:'makkah',g:'hajj',i:'🌄',n:'Mount Arafat & Jabal ar-Rahmah',q:'Jabal ar-Rahmah Arafat',d:'The plain of the Farewell Sermon where Hajj reaches its peak — "Hajj is Arafah." Standing here on 9 Dhul-Hijjah is the heart of Hajj.',tip:'Combine Arafat, Muzdalifah & Mina in one half-day ziyarah taxi tour (agree the price first).'},
{id:'namirah',ll:[21.354,39.9707],city:'makkah',g:'hajj',i:'🕌',n:'Masjid Namirah (Arafat)',q:'Masjid Namirah Arafat',d:'The Prophet ﷺ had his tent pitched at Namirah on the day of Arafah, then addressed the people and prayed Dhuhr and Asr combined (Muslim 1218). One of the largest mosques in the world.',tip:'Opens only on the day of Arafah; outside Hajj you view it from the road.'},
{id:'muzdalifah',ll:[21.3833,39.9366],city:'makkah',g:'hajj',i:'🌌',n:'Muzdalifah',q:'Muzdalifah',d:'Where Hajj pilgrims sleep under the open sky between Arafat and Mina — named in the Quran as al-Mash’ar al-Haram (2:198).',tip:'Drive-through on a ziyarah tour; picture two million people sleeping here in one night.'},
{id:'mashar',city:'makkah',g:'hajj',i:'🕌',n:'Masjid al-Mash’ar al-Haram',q:'Masjid Al Mashar Al Haram Muzdalifah',d:'Marks the spot where the Prophet ﷺ stood at Muzdalifah making dua until the sky brightened — "remember Allah at al-Mash’ar al-Haram" (Quran 2:198).',tip:'Between Arafat and Mina on the pilgrim road.'},
{id:'mina',ll:[21.4133,39.8933],city:'makkah',g:'hajj',i:'⛺',n:'Mina',q:'Mina Makkah',d:'The tent city of Hajj — 100,000 fireproof tents — and the site of the Jamarat and the sacrifice.',tip:'Quiet outside Hajj season — a moving drive-through with Quran 22:27 in mind.'},
{id:'khayf',ll:[21.419,39.888],city:'makkah',g:'hajj',i:'🕌',n:'Masjid al-Khayf (Mina)',q:'Masjid Al Khaif Mina',d:'The great mosque of Mina where the Prophet ﷺ prayed during his Hajj; narrations reported by at-Tabarani say many prophets before him prayed in this valley.',tip:'Holds 45,000; outside Hajj it is open and near-empty — pray two rakahs.'},
{id:'bayah',city:'makkah',g:'hajj',i:'🤝',n:'Masjid al-Bay’ah (Aqabah)',q:'Masjid Al Bayah Mina',d:'Where the people of Madinah secretly pledged allegiance to the Prophet ﷺ in the two Pledges of Aqabah (621–622 CE) — the moment that opened the door to the Hijrah.',tip:'A small, easily-missed mosque near the Jamarat bridge; built in 144 AH.'},
{id:'jamarat',ll:[21.4224,39.8735],city:'makkah',g:'hajj',i:'🪨',n:'The Jamarat',q:'Jamarat Bridge Mina',d:'The three pillars marking where Ibrahim (AS) stoned Shaytan when tempted to disobey — re-enacted by every Hajj pilgrim on the days of Tashriq.',tip:'The multi-level bridge is an engineering marvel; visit outside Hajj to understand the layout before you ever come for Hajj.'},
/* ── MAKKAH · Museums & culture ── */
{id:'hirac',ll:[21.456,39.857],city:'makkah',g:'museum',i:'🏛️',n:'Hira Cultural District & Revelation Exhibition',q:'Hira Cultural District Makkah',d:'A modern museum at the foot of Jabal an-Nour telling the story of wahy (revelation) with immersive exhibits — the context for everything you recite.',tip:'The perfect alternative to the climb for the elderly and children. Book online; evening slots are cooler.'},
{id:'exhibition',city:'makkah',g:'museum',i:'🏛️',n:'Exhibition of the Two Holy Mosques',q:'Exhibition of the Two Holy Mosques Architecture Makkah',d:'Historic Kaaba doors, kiswah textiles, the old Zamzam well-head, Maqam Ibrahim casings and rare artefacts of the Haramain across the centuries.',tip:'Free entry; on the old Jeddah road. Check hours before going.'},
{id:'kiswah',city:'makkah',g:'museum',i:'🧵',n:'The Kiswah Factory (King Abdulaziz Complex)',q:'Kiswa Factory Makkah',d:'Where the black silk covering of the Kaaba is woven each year and embroidered with 120 kg of gold and silver thread — a craft of honouring the House that is centuries old.',tip:'Visits are by arrangement/tour; the exhibition explains every panel of calligraphy you see on the Kaaba.'},
{id:'makkahmuseum',city:'makkah',g:'museum',i:'🏛️',n:'Makkah Museum (Al-Zahir Palace)',q:'Makkah Museum Al Zahir Palace',d:'The history of the Hijaz from pre-Islamic times through the prophetic era to the modern Kingdom, in a 1940s palace.',tip:'Mornings, weekdays; combine with the Exhibition of the Two Holy Mosques nearby.'},
{id:'clock',ll:[21.4187,39.8256],city:'makkah',g:'museum',i:'🕰️',n:'Makkah Clock Tower Museum',q:'Clock Tower Museum Makkah',d:'Astronomy and Islamic timekeeping museum atop the Abraj al-Bait — four floors, then a breathtaking balcony view over the Haram.',tip:'Book in advance; sunset slots have the best views.'},
/* ── MAKKAH · Day trips ── */
{id:'taif',ll:[21.2705,40.4158],city:'makkah',g:'trip',i:'🌹',n:'Ta’if & Masjid Abdullah ibn Abbas',q:'Masjid Abdullah Ibn Abbas Taif',d:'The mountain city that stoned the Prophet ﷺ in the 10th year of his mission — when the Angel of the Mountains offered to crush it, he refused, hoping for believing descendants (Bukhari 3231). Today: cool air, rose farms, and the mosque of Ibn Abbas (RA).',tip:'~1.5 h by road up the escarpment. Wadi Muharram on the way is a miqat if you return in ihram.'},
{id:'jeddah',ll:[21.4858,39.1875],city:'makkah',g:'trip',i:'🏘️',n:'Historic Jeddah (Al-Balad)',q:'Al Balad Jeddah',d:'The UNESCO-listed old town that was the sea gate of pilgrims to Makkah for thirteen centuries — coral-stone houses, wooden rawashin balconies, ancient mosques.',tip:'An evening stroll on the way to the airport. A cultural, not religious, visit.'},
/* ── MADINAH · The Prophet’s Mosque & around ── */
{id:'nabawi',ll:[24.4672,39.6111],city:'madinah',g:'mharam',i:'🕌',n:'Masjid an-Nabawi',q:'Al Masjid an Nabawi Madinah',d:'The Prophet’s ﷺ mosque, built with his own hands — one prayer here is better than a thousand elsewhere (Bukhari 1190).',tip:'Give salam to the Prophet ﷺ and his two companions with calm and lowered voice.',stop:'G1'},
{id:'rawdah',ll:[24.4672,39.6111],city:'madinah',g:'mharam',i:'🌹',n:'The Rawdah',q:'Al Masjid an Nabawi Madinah',d:'"Between my house and my minbar is a garden from the gardens of Paradise" (Bukhari 1195).',tip:'Requires a free timed permit on the Nusuk app — book the moment your dates are fixed.'},
{id:'babsalam',ll:[24.4677,39.6104],city:'madinah',g:'mharam',i:'🚪',n:'Bab as-Salam (Al Salam Gate)',q:'Bab As Salam Al Masjid an Nabawi',d:'The historic western gate of the mosque — for centuries the traditional entrance by which visitors approach to greet the Prophet ﷺ, Abu Bakr and ’Umar.',tip:'Walk it slowly with salawat on your lips; no crowding, no raised voices.',stop:'G4'},
{id:'baqi',ll:[24.4668,39.6169],city:'madinah',g:'mharam',i:'🌿',n:'Jannat al-Baqi’',q:'Al Baqi Cemetery Madinah',d:'Resting place of ’Uthman (RA), the Prophet’s ﷺ wives and daughters, his son Ibrahim, and some ten thousand companions.',tip:'Open after Fajr and Asr; entry for men. Give the sunnah salam to the people of the graves.',stop:'G2'},
{id:'manakha',ll:[24.4672,39.608],city:'madinah',g:'mharam',i:'🏙️',n:'Al Manakha Square',q:'Al Manakha Square Madinah',d:'The old caravan-halt and market ground west of the mosque — the Prophet ﷺ moved Madinah’s market here, saying "this is your market". Masjid al-Ghamamah stands on its edge.',tip:'Dates, cafés and evening buzz; a good meeting point for families.',stop:'G3'},
{id:'quranmuseum',city:'madinah',g:'mharam',i:'📖',n:'Exhibition of the Holy Quran & the Prophet’s Biography',q:'International Fair and Museum of the Prophet Biography Madinah',d:'Two museums beside the Haram: rare mushafs and the science of the Quran, and a sensory walk through the seerah.',tip:'Wonderful with children; tours in many languages.'},
/* ── MADINAH · Historic mosques ── */
{id:'quba',ll:[24.4396,39.6172],city:'madinah',g:'mosques',i:'🕌',n:'Masjid Quba',q:'Quba Mosque Madinah',d:'The first mosque of Islam, "founded on taqwa" (Quran 9:108). Praying 2 rakahs here with wudu from home earns the reward of an Umrah (Ibn Majah 1412).',tip:'The Prophet ﷺ visited every Saturday, walking or riding (Bukhari 1194) — make wudu at your hotel and go at least once.',stop:'R6'},
{id:'qiblatain',ll:[24.4842,39.5934],city:'madinah',g:'mosques',i:'🕌',n:'Masjid al-Qiblatayn',q:'Masjid al-Qiblatayn Madinah',d:'Where the revelation to turn the qibla from Jerusalem to Makkah came mid-prayer (Quran 2:144) — the congregation turned as one.',tip:'A short ride north-west of the Haram; combine with the Seven Mosques.',stop:'R4'},
{id:'jumuah',ll:[24.4497,39.6153],city:'madinah',g:'mosques',i:'🕌',n:'Masjid al-Jumu’ah',q:'Masjid Al Jumuah Madinah',d:'In the valley of Ranuna, where the Prophet ﷺ prayed the first Friday prayer in Islam on the way from Quba into Madinah after the Hijrah.',tip:'Halfway along Quba Avenue — stop here if you walk to Quba.'},
{id:'ijabah',ll:[24.4737,39.618],city:'madinah',g:'mosques',i:'🤲',n:'Masjid al-Ijabah',q:'Masjid Al Ijabah Madinah',d:'The mosque of Banu Mu’awiyah where the Prophet ﷺ prayed and made a long dua: "I asked my Lord three things — He granted me two and withheld one" (Muslim 2890).',tip:'5 min from Baqi on Sitteen Street; pray two rakahs and make your own long dua.'},
{id:'ghamamah',ll:[24.4665,39.6096],city:'madinah',g:'mosques',i:'🕌',n:'Masjid al-Ghamamah',q:'Masjid al-Ghamamah Madinah',d:'Where the Prophet ﷺ prayed Eid and istisqa (the rain prayer) — a cloud (ghamamah) is said to have shaded him here.',tip:'A 5-minute walk south-west of Masjid an-Nabawi, beside Al Manakha.'},
{id:'miqat',ll:[24.4137,39.5433],city:'madinah',g:'mosques',i:'🤍',n:'Masjid al-Miqat (Dhul-Hulayfah / Abyar Ali)',q:'Masjid Al Miqat Abyar Ali Madinah',d:'The miqat the Prophet ﷺ appointed for the people of Madinah (Bukhari 1524) — where you will assume ihram before travelling to Makkah, as he did.',tip:'9 km south-west. Showers, wudu areas and ihram shops on site; the Haramain train and most buses stop here on request.'},
/* ── MADINAH · Battlefields, wells & history ── */
{id:'uhud',ll:[24.504,39.613],city:'madinah',g:'history',i:'⛰️',n:'Mount Uhud & the Martyrs’ Cemetery',q:'Mount Uhud Madinah',d:'Site of the Battle of Uhud (3 AH) — resting place of Hamza (RA) and seventy martyrs. "Uhud is a mountain that loves us and we love it" (Bukhari 4083).',tip:'Visit after Fajr before the heat; give salam at the martyrs’ fence and climb the Archers’ Hill to understand the battle.',stop:'R1'},
{id:'khandaq',ll:[24.474,39.599],city:'madinah',g:'history',i:'🕌',n:'The Trench Battlefield & the Seven Mosques',q:'Seven Mosques Madinah',d:'Where the Muslims dug the trench at the foot of Mount Sila’ in 5 AH and Allah sent the wind against the confederates (Quran 33:9). Small mosques mark the posts of the Prophet ﷺ, Salman, Abu Bakr, ’Umar, ’Ali and Fatimah.',tip:'Masjid al-Fath on the hill is where the Prophet ﷺ prayed for victory. Minutes from Qiblatayn.',stop:'R5'},
{id:'aqiq',city:'madinah',g:'history',i:'🏞️',n:'Wadi al-Aqiq',q:'Wadi Al Aqiq Madinah',d:'"A messenger came to me from my Lord and said: pray in this blessed valley" (Bukhari 1534). The valley of Madinah’s old estates and the path to the miqat.',tip:'You cross it on the way to Masjid al-Miqat — look out for it.'},
{id:'biruthman',city:'madinah',g:'history',i:'💧',n:'Bir Uthman (the Well of Rumah)',q:'Bir Uthman Madinah',d:'’Uthman (RA) bought this well and made it free for all Muslims after the Prophet ﷺ said: "Whoever buys the well of Rumah will have Paradise" (Bukhari 2778, Tirmidhi 3703). Its endowment still funds charity 1,400 years later.',tip:'A working date farm north of the city; a lesson in sadaqah jariyah.'},
{id:'salman',city:'madinah',g:'history',i:'🌴',n:'Garden of Salman al-Farisi',q:'Salman Al Farsi Garden Madinah',d:'The palm garden associated with Salman’s (RA) freedom — reports say the Prophet ﷺ planted the date palms with his own hands to pay the price of his manumission.',tip:'Near Quba; a quiet place to reflect on a seeker who crossed empires to find the truth.'},
{id:'hijazrail',ll:[24.4653,39.605],city:'madinah',g:'history',i:'🚂',n:'Al Hijaz Railway Station & Museum',q:'Hejaz Railway Museum Madinah',d:'The 1908 Ottoman terminus of the Damascus–Madinah line, built to carry pilgrims to the Haramain. The restored station is now a museum of Madinah’s history and the railway.',tip:'Check opening — parts have been closed for restoration. Hop-on hop-off stop.',stop:'R7'},
{id:'darmadinah',city:'madinah',g:'history',i:'🏛️',n:'Dar Al Madinah Museum',q:'Dar Al Madinah Museum',d:'The seerah and the history of Madinah with detailed models of the city across the ages.',tip:'Excellent with kids; guided tours available in English.'},
/* ── MADINAH · Hop-on hop-off & practical ── */
{id:'qubasq',ll:[24.445,39.616],city:'madinah',g:'tour',i:'🚶',n:'Quba Square & Quba Avenue',q:'Quba Avenue Madinah',d:'The 3 km palm-lined pedestrian avenue from the Haram to Masjid Quba — walk it as the Prophet ﷺ did on his Saturday visits (Bukhari 1194).',tip:'Walk it at sunset; the bus brings you back. Hop-on hop-off stop.',stop:'R8'},
{id:'noormall',city:'madinah',g:'tour',i:'🛍️',n:'Al-Noor Mall',q:'Al Noor Mall Madinah',d:'Madinah’s largest mall — a practical hop-off for food courts, kids’ areas, pharmacies and gifts.',tip:'Handy between Uhud and Qiblatayn on the Red route.',stop:'R2'},
{id:'sultanah',city:'madinah',g:'tour',i:'🍽️',n:'Sultanah — Abu Bakr as-Siddiq Road',q:'Sultanah Road Madinah',d:'The main restaurant and shopping strip — Madinah dates, perfume, and the city’s best-known eateries.',tip:'Try the local Ajwa dates and the famous Madinah bukhari rice.',stop:'R3'}];

var QUIZ_LEVELS=[
{icon:'🕋',name:'Level 1 · Foundations of Umrah',desc:'What Umrah is and how it flows',qs:[
{q:'Umrah is often called…',o:['The greater pilgrimage','The minor pilgrimage','The night journey','The farewell pilgrimage'],a:1,e:'Umrah is the "minor pilgrimage" — Hajj is the major one with fixed dates and extra rites.'},
{q:'True or false: Umrah can be performed at any time of the year.',tf:1,a:0,e:'True — unlike Hajj, Umrah has no fixed date. (Ramadan carries a special reward.)'},
{q:'The correct order of the Umrah rites is…',o:['Tawaf → Ihram → Sa’i → Halq','Ihram → Sa’i → Tawaf → Halq','Ihram → Tawaf → Sa’i → Halq/Taqsir','Sa’i → Tawaf → Ihram → Halq'],a:2,e:'Ihram at the miqat, then tawaf, then sa’i, then cutting the hair — in that order.'},
{q:'True or false: Umrah and Hajj are identical acts of worship.',tf:1,a:1,e:'False — Hajj adds Arafat, Muzdalifah, Mina and the fixed days of Dhul-Hijjah; Umrah is ihram, tawaf, sa’i and halq.'},
{q:'How many rounds (circuits) make one complete tawaf?',o:['3','5','7','10'],a:2,e:'Seven rounds, counter-clockwise, starting and ending at the Black Stone line.'},
{q:'Sa’i begins at… and ends at…',o:['Marwah → Safa','Safa → Marwah','Either direction','The mataf'],a:1,e:'"Begin with what Allah began with" — Quran 2:158 mentions Safa first; 7 laps ending at Marwah.'},
{q:'When does the pilgrim stop reciting the talbiyah in Umrah?',o:['At the hotel','On seeing the Kaaba','When beginning tawaf','After sa’i'],a:2,e:'The talbiyah continues from the miqat until you start your tawaf.'},
{q:'What does "Labbayk" mean?',o:['Forgive me','Here I am (at Your service)','Allah is greatest','Praise be to Allah'],a:1,e:'Labbayk Allahumma labbayk — "Here I am, O Allah, here I am," answering the call to pilgrimage.'},
{q:'True or false: children may perform Umrah, with guardians handling the rites for the very young.',tf:1,a:0,e:'True — the Prophet ﷺ confirmed a child’s pilgrimage counts (Muslim 1336); parents make intention for infants.'},
{q:'True or false: an accepted pilgrimage returns you "as the day your mother bore you".',tf:1,a:0,e:'True — whoever performs it without obscenity or sin returns cleansed of sins (Bukhari 1521, Muslim 1350).'}
]},
{icon:'🤍',name:'Level 2 · Ihram & the Miqats',desc:'The sacred state and its boundaries',qs:[
{q:'The miqat for those travelling to Makkah from Madinah is…',o:['Yalamlam','Qarn al-Manazil','Al-Juhfah','Dhul-Hulayfah (Abyar Ali)'],a:3,e:'Dhul-Hulayfah, just outside Madinah — the farthest miqat from Makkah (~450 km).'},
{q:'Most flights arriving from the east (UAE, Pakistan, India…) cross which miqat?',o:['Qarn al-Manazil (As-Sayl)','Al-Juhfah','Dhat Irq','Yalamlam'],a:0,e:'Qarn al-Manazil serves Najd, Taif and most eastern arrivals — be in ihram before the pilot’s announcement.'},
{q:'Which of these is prohibited in ihram?',o:['Wearing a wristwatch','Showering with plain water','Applying perfume','Wearing sandals'],a:2,e:'Scented products are prohibited. Watches, glasses, belts and unscented showers are all fine.'},
{q:'True or false: men may wear a money belt or waist pouch in ihram.',tf:1,a:0,e:'True — a belt is not fitted "stitched clothing"; it is how you keep your passport and cash safe.'},
{q:'True or false: a woman must wear a niqab (face veil) in ihram.',tf:1,a:1,e:'False — the opposite: the niqab and gloves are specifically not worn in ihram (Bukhari 1838). Ordinary modest dress applies.'},
{q:'The two garments of a man’s ihram are called…',o:['Thobe & ghutrah','Izar & rida','Bisht & shemagh','Qamis & sirwal'],a:1,e:'The izar wraps the lower body, the rida drapes the upper body — both unstitched.'},
{q:'True or false: the intention for Umrah must be made before crossing the miqat.',tf:1,a:0,e:'True — crossing your miqat without ihram when intending Umrah requires returning to it or compensation (fidyah).'},
{q:'True or false: a pilgrim flying to Jeddah may delay ihram until after landing.',tf:1,a:1,e:'False — Jeddah lies inside the miqat boundaries for most routes, so ihram must be assumed before the plane crosses the miqat.'},
{q:'Which is NOT an ihram violation?',o:['Applying perfume','Trimming nails','Wearing prescription glasses','Proposing marriage'],a:2,e:'Glasses, watches, rings, umbrellas and sandals are all fine in ihram.'},
{q:'True or false: if you break an ihram rule by genuine mistake or forgetfulness, your Umrah is ruined.',tf:1,a:1,e:'False — "Our Lord, do not hold us to account for what we forget or err in" (Quran 2:286). Learn, correct, continue.'}
]},
{icon:'🔄',name:'Level 3 · Tawaf, Sa’i & Halq',desc:'The rites in fine detail',qs:[
{q:'Where does each round of tawaf begin?',o:['Maqam Ibrahim','The Black Stone (Hajar al-Aswad) corner','The Yamani corner','The Kaaba door'],a:1,e:'Face the Black Stone, say "Bismillahi wallahu akbar", then keep the Kaaba on your left.'},
{q:'What is raml?',o:['Brisk walking in the first 3 rounds of tawaf (men)','Jogging the whole sa’i','A type of dua','The stoning ritual'],a:0,e:'Men walk briskly with short steps in rounds 1–3 of the arrival tawaf only. Women walk normally.'},
{q:'True or false: wudu is required for tawaf.',tf:1,a:0,e:'True — tawaf is like prayer (Tirmidhi 960); keep your wudu, and renew it if broken.'},
{q:'True or false: each round of tawaf has its own fixed, prescribed dua.',tf:1,a:1,e:'False — no dua is prescribed per round. Only "Rabbana atina…" between the Yamani corner and Black Stone is sunnah.'},
{q:'You cannot reach the Black Stone. What do you do?',o:['Push through the crowd','Skip that round','Point towards it and say Allahu Akbar','Wait until it clears'],a:2,e:'Gesture from afar with "Allahu Akbar" and continue — harming others for a sunnah is never right.'},
{q:'What dua is sunnah between the Yamani corner and the Black Stone?',o:['The talbiyah','Rabbana atina fid-dunya hasanah…','Ayat al-Kursi','Surah al-Fatihah'],a:1,e:'"Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire." (Quran 2:201)'},
{q:'What is prayed immediately after tawaf?',o:['4 rakahs of Duha','2 rakahs behind Maqam Ibrahim','Salat al-Janazah','Nothing'],a:1,e:'Two rakahs behind Maqam Ibrahim (anywhere if crowded) — al-Kafirun then al-Ikhlas are sunnah.'},
{q:'True or false: Safa → Marwah counts as one full lap of sa’i.',tf:1,a:0,e:'True — one direction is one lap; seven laps finish on Marwah.'},
{q:'True or false: women jog between the green lights during sa’i.',tf:1,a:1,e:'False — the light jog there is for men; women walk throughout.'},
{q:'How does a woman exit ihram after sa’i?',o:['Shave her head','Trim a fingertip’s length of hair','Cut a single strand','Nothing required'],a:1,e:'Women trim about a fingertip’s length (~2 cm) from the ends — never shave.'},
{q:'True or false: for men, shaving the head (halq) carries more reward than trimming (taqsir).',tf:1,a:0,e:'True — the Prophet ﷺ made dua for those who shave three times, and once for those who trim (Bukhari 1727).'}
]},
{icon:'🕰️',name:'Level 4 · History of Makkah & the Kaaba',desc:'The story behind every rite',qs:[
{q:'Who raised the foundations of the Kaaba?',o:['Adam alone','Ibrahim & Isma’il','Quraysh','Musa & Harun'],a:1,e:'"And when Ibrahim was raising the foundations of the House with Isma’il…" (Quran 2:127).'},
{q:'The Kaaba is described in the Quran as…',o:['The first House established for mankind','The largest building of its time','A gift to Quraysh','The house of Adam'],a:0,e:'"The first House established for mankind was that at Bakkah — blessed and a guidance for the worlds." (Quran 3:96)'},
{q:'The well of Zamzam sprang for…',o:['Ibrahim on his journey','Hajar and baby Isma’il','The army of the Elephant','Quraysh pilgrims'],a:1,e:'Allah caused it to spring at baby Isma’il’s feet as Hajar ran between Safa and Marwah (Bukhari 3364).'},
{q:'Sa’i between Safa and Marwah commemorates…',o:['The Hijrah route','Hajar’s search for water','The conquest of Makkah','The Farewell Sermon'],a:1,e:'Your seven laps re-enact Hajar’s seven runs of pure trust in Allah — "Then He will not abandon us."'},
{q:'True or false: the Black Stone descended from Paradise whiter than milk.',tf:1,a:0,e:'True — "…and the sins of the children of Adam blackened it." (Tirmidhi 877)'},
{q:'How did the young Muhammad ﷺ resolve the Quraysh dispute over placing the Black Stone?',o:['He placed it himself secretly','He drew lots','He laid it on a cloth for all tribes to lift together','He told them to leave it out'],a:2,e:'Every tribe lifted a corner of the cloth, and al-Amin ﷺ set the Stone in place with his own hands.'},
{q:'The first revelation came to the Prophet ﷺ in…',o:['The cave of Thawr','Masjid al-Haram','The cave of Hira on Jabal an-Nour','Mina'],a:2,e:'"Iqra — Read!" (Quran 96:1) descended in Hira, the cave above Makkah (Bukhari 3).'},
{q:'True or false: Muslims always prayed towards the Kaaba from the beginning of Islam.',tf:1,a:1,e:'False — they first faced Jerusalem; the qibla changed mid-prayer (~2 AH) — Quran 2:144, commemorated at Masjid al-Qiblatayn.'},
{q:'Maqam Ibrahim is…',o:['Ibrahim’s grave','The stone he stood on while building the Kaaba','The door of the Kaaba','A minaret'],a:1,e:'The standing-stone of Ibrahim (AS) — "Take the Maqam of Ibrahim as a place of prayer." (Quran 2:125)'},
{q:'During the Hijrah, the Prophet ﷺ and Abu Bakr hid in…',o:['The cave of Hira','The cave of Thawr','Masjid Quba','Jabal Uhud'],a:1,e:'Three nights in Thawr — "Do not grieve; indeed Allah is with us." (Quran 9:40)'},
{q:'True or false: praying inside Hijr Isma’il counts as praying inside the Kaaba.',tf:1,a:0,e:'True — the semicircle was part of the original Kaaba (Tirmidhi 876). A rare chance most pilgrims miss!'}
]},
{icon:'🌟',name:'Level 5 · Virtues of Umrah & the Haram',desc:'The rewards that await you',qs:[
{q:'"Umrah to Umrah is an expiation for…"',o:['All future sins','The sins committed between them','Major sins only','Debts'],a:1,e:'Bukhari 1773 — and the accepted Hajj has no reward but Paradise.'},
{q:'What does "an Umrah in Ramadan" equal, according to the Prophet ﷺ?',o:['10 Umrahs','A Hajj with him ﷺ','Laylatul Qadr','A year of fasting'],a:1,e:'"An Umrah in Ramadan is equal to a Hajj" (Bukhari 1863) — and in one narration: "a Hajj with me" (Muslim 1256).'},
{q:'One prayer in Masjid al-Haram equals how many elsewhere?',o:['1,000','10,000','50,000','100,000'],a:3,e:'100,000 prayers (Ibn Majah 1406) — one Fajr there outweighs decades of prayer elsewhere.'},
{q:'True or false: "Follow up between Hajj and Umrah, for they remove poverty and sins…"',tf:1,a:0,e:'True — "…as the bellows removes the dross of iron, gold and silver." (Tirmidhi 810)'},
{q:'Pilgrims are described by the Prophet ﷺ as…',o:['The soldiers of Allah','The delegation (guests) of Allah','The neighbours of the Kaaba','The people of the cloak'],a:1,e:'"If they call upon Him, He answers; if they seek His forgiveness, He forgives." (Ibn Majah 2892)'},
{q:'True or false: the Prophet ﷺ called Hajj and Umrah the jihad of the elderly, the young, the weak and women.',tf:1,a:0,e:'True — "The jihad of the elderly, the young, the weak and women is Hajj and Umrah" (Nasai 2626); and to Aishah (RA): "jihad in which there is no fighting" (Ibn Majah 2901).'},
{q:'Completing tawaf while keeping count of it is likened to…',o:['Fasting a month','Freeing a slave','A year of charity','Building a mosque'],a:1,e:'Tirmidhi 959 — and with every step a sin is erased and a good deed recorded.'},
{q:'"Zamzam water is…"',o:['Only for the sick','For whatever it is drunk for','Only for pilgrims','For wudu only'],a:1,e:'Ibn Majah 3062 — drink it with a specific dua: knowledge, cure, forgiveness, whatever you need.'},
{q:'True or false: the Prophet ﷺ called Makkah the most beloved of Allah’s land to Allah.',tf:1,a:0,e:'True — "Had I not been driven out of you, I would never have left." (Tirmidhi 3925)'},
{q:'True or false: because the Haram multiplies reward, wrongdoing there is also graver.',tf:1,a:0,e:'True — Allah warns against "deviation to wrongdoing" in the Haram (Quran 22:25). Guard your tongue and gaze doubly.'}
]},
{icon:'🕌',name:'Level 6 · Madinah — City of the Prophet ﷺ',desc:'Virtues & etiquette of the visit',qs:[
{q:'One prayer in Masjid an-Nabawi is better than…',o:['100 elsewhere','1,000 elsewhere (except al-Masjid al-Haram)','100,000 elsewhere','70 elsewhere'],a:1,e:'Bukhari 1190 — a thousand-fold, exceeded only by Masjid al-Haram.'},
{q:'The Rawdah is described by the Prophet ﷺ as…',o:['The best of gardens','A garden from the gardens of Paradise','His private courtyard','The first masjid'],a:1,e:'"Between my house and my minbar is a garden from the gardens of Paradise." (Bukhari 1195)'},
{q:'Visiting the Rawdah requires…',o:['Nothing — walk in anytime','A paid ticket','A free timed permit via the Nusuk app','A tour guide'],a:2,e:'Book the free permit on Nusuk as soon as your dates are confirmed — slots run out.'},
{q:'Praying 2 rakahs in Masjid Quba (with wudu from home) equals…',o:['A Hajj','An Umrah','40 years of prayer','Nothing specific'],a:1,e:'Ibn Majah 1412 — and the Prophet ﷺ visited Quba every Saturday.'},
{q:'True or false: Madinah is a sacred sanctuary (haram) just as Makkah is.',tf:1,a:0,e:'True — the Prophet ﷺ declared Madinah sacred between its two lava plains (Muslim 1374).'},
{q:'True or false: the Dajjal and the plague can enter Madinah.',tf:1,a:1,e:'False — "There are angels at the entrances of Madinah: neither plague nor the Dajjal can enter it." (Bukhari 1880)'},
{q:'Masjid al-Qiblatayn is famous because…',o:['It has two minarets','The qibla changed there mid-prayer','It is the oldest mosque','The Prophet ﷺ was born there'],a:1,e:'The congregation turned from Jerusalem to the Kaaba in a single prayer (Quran 2:144).'},
{q:'The Prophet ﷺ said about Uhud…',o:['"It is a cursed mountain"','"It is a mountain that loves us and we love it"','"Never climb it"','"It guards the city"'],a:1,e:'Bukhari 4083 — at its foot rest Hamza (RA) and the seventy martyrs of Uhud.'},
{q:'Who rests beside the Prophet ﷺ in his chamber?',o:['Hamza & Abbas','Abu Bakr & Umar','Uthman & Ali','His wives'],a:1,e:'His two closest companions and successors — greet all three with a calm salam.'},
{q:'True or false: visiting Madinah is a required rite of Umrah.',tf:1,a:1,e:'False — beloved and highly virtuous (one of the three mosques worth travelling to — Bukhari 1189), but not part of the Umrah rites, and it needs no ihram.'},
{q:'"Whoever eats seven ___ dates in the morning will not be harmed that day by poison or magic."',o:['Sukkari','Ajwa','Medjool','Barhi'],a:1,e:'Ajwa dates of Madinah (Bukhari 5779) — the perfect gift to bring home.'},
{q:'True or false: the Prophet ﷺ will intercede for the one who dies in Madinah.',tf:1,a:0,e:'True — "Whoever is able to die in Madinah, let him die there, for I will intercede for him." (Tirmidhi 3917)'}
]},
{icon:'⚖️',name:'Level 7 · Fiqh essentials — Q&A',desc:'The rulings first-timers ask about',qs:[
{q:'Can you perform Umrah on behalf of a deceased parent?',o:['Never','Yes — after having performed your own Umrah first','Only during Hajj season','Only for mothers'],a:1,e:'Badal is established: "Labbayk on behalf of Shubrumah…" — the Prophet ﷺ said to perform your own first, then his (Abu Dawud 1811).'},
{q:'True or false: you may perform a second Umrah in the same trip by taking ihram from Tan’eem.',tf:1,a:0,e:'True — the Prophet ﷺ sent Aishah (RA) with her brother to Tan’eem for exactly this (Bukhari 1784).'},
{q:'How many Umrahs did the Prophet ﷺ perform?',o:['One','Two','Four','Seven'],a:2,e:'Four: Hudaybiyyah, al-Qada, al-Ji’ranah, and the one with his Hajj (Bukhari 1778).'},
{q:'Your wudu breaks in round 5 of tawaf. What happens?',o:['The whole Umrah is invalid','Renew wudu and continue — completed rounds are not lost','You must restart from round 1 tomorrow','Nothing — wudu is optional'],a:1,e:'Renew your wudu and return; resume the interrupted round (or repeat it to be safe). No panic, nothing is ruined.'},
{q:'True or false: you may pause tawaf or sa’i to rest, drink Zamzam, or join the obligatory prayer, then continue.',tf:1,a:0,e:'True — continue from where you left off. "Allah intends for you ease" (Quran 2:185).'},
{q:'A woman’s period begins after ihram. She…',o:['Cannot do Umrah at all','Continues everything except tawaf (and the sa’i after it) until pure','Does tawaf anyway','Must leave Makkah immediately'],a:1,e:'Ihram, talbiyah, dhikr and dua all continue; only the tawaf (and its sa’i) wait for purity (Bukhari 305).'},
{q:'True or false: skipping raml or idtiba’ invalidates the tawaf.',tf:1,a:1,e:'False — both are sunnah for men in the arrival tawaf only; leaving them affects nothing.'},
{q:'Tawaf in a wheelchair or on the upper floors is…',o:['Invalid','Valid only for the elderly','Fully valid','Half reward'],a:2,e:'Fully valid — the Prophet ﷺ himself performed tawaf mounted (Bukhari 1607).'},
{q:'True or false: speaking during tawaf breaks it, exactly like speaking in salah.',tf:1,a:1,e:'False — "Tawaf is like salah, except that Allah permitted speech in it; so speak only good." (Tirmidhi 960)'},
{q:'True or false: a man’s ihram garments must be brand new and pure white.',tf:1,a:1,e:'False — clean and unstitched is the requirement; white is recommended, new is not. Spares and washing are fine.'}
]}];

var DUAS=[
{t:'The Talbiyah',ar:'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ',tl:'Labbayk Allahumma labbayk, labbayka la sharika laka labbayk, innal-hamda wan-ni’mata laka wal-mulk, la sharika lak',tr:'Here I am O Allah, here I am. You have no partner, here I am. All praise, favour and sovereignty are Yours. You have no partner.',s:'Bukhari 1549'},
{t:'Entering the mosque',ar:'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',tl:'Allahumma-ftah li abwaba rahmatik',tr:'O Allah, open for me the gates of Your mercy.',s:'Muslim 713'},
{t:'Leaving the mosque',ar:'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',tl:'Allahumma inni as’aluka min fadlik',tr:'O Allah, I ask You of Your bounty.',s:'Muslim 713'},
{t:'Between the Yamani corner & Black Stone',ar:'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',tl:'Rabbana atina fid-dunya hasanah wa fil-akhirati hasanah wa qina ’adhaban-nar',tr:'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',s:'Quran 2:201 · Abu Dawud 1892'},
{t:'On Safa & Marwah',ar:'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',tl:'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa ’ala kulli shay’in qadir',tr:'None has the right to be worshipped but Allah alone, without partner. His is the dominion and the praise, and He is able to do all things. (Repeat 3× with your own duas between.)',s:'Muslim 1218'},
{t:'When drinking Zamzam',ar:'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا وَاسِعًا وَشِفَاءً مِنْ كُلِّ دَاءٍ',tl:'Allahumma inni as’aluka ’ilman nafi’an wa rizqan wasi’an wa shifa’an min kulli da’',tr:'O Allah, I ask You for beneficial knowledge, abundant provision, and cure from every illness. (Reported from Ibn Abbas RA)',s:'"Zamzam is for whatever it is drunk for" — Ibn Majah 3062'},
{t:'The travel dua',ar:'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ',tl:'Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqalibun',tr:'Glory to Him who has subjected this to us, and we could never have it by our efforts. Surely to our Lord we are returning.',s:'Quran 43:13-14 · Muslim 1342'},
{t:'Salam upon the Prophet ﷺ (in Madinah)',ar:'السَّلَامُ عَلَيْكَ يَا رَسُولَ اللَّهِ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ',tl:'As-salamu ’alayka ya Rasulallah wa rahmatullahi wa barakatuh',tr:'Peace be upon you, O Messenger of Allah, and the mercy of Allah and His blessings. (Then salam upon Abu Bakr and ’Umar.)',s:'Etiquette: calm voice, no crowding'}];

var BADGES=[
{id:'firstUmrah',name:'First Umrah',icon:'🕋'},
{id:'again',name:'Again & Again',icon:'🔁'},
{id:'quizMaster',name:'Quiz Master',icon:'🧠'},
{id:'prepped',name:'Fully Prepped',icon:'🧳'},
{id:'explorer',name:'Explorer',icon:'📍'},
{id:'devoted',name:'Devoted',icon:'🕌'},
{id:'quranComp',name:'Quran Companion',icon:'📖'},
{id:'nightHaram',name:'Night in the Haram',icon:'🌙'}];
